### PR TITLE
Look for a global rustfmt.toml.

### PR DESCRIPTION
**Pull request by m-ou-se**
If no rustfmt.toml is found in the usual way, the directory 'rustfmt' in
the user's config directory is checked.

 - $XDG_CONFIG_HOME/rustfmt/ (or $HOME/.config/rustfmt/), or
 - $HOME/Library/Preferences/rustfmt/ on Mac, or
 - %AppData%\rustfmt\ on Windows.

### CODE REVIEW

**Comment by otavio** [comment]
I agree with the idea here however I think we ought also to allow user to add it to `$HOME/.rustfmt.toml` as a lot of other tools do since ages. I understand the tendency of adopting the XDG but old Unix guys might also have their old habits respected.

Do you guys see a problem with this?

**Comment by otavio** [comment]
> In general I have no problem with tools _also_ supporting the 'old' way of putting configuration directly in `$HOME`, as long as tools don't write stuff there by themselves.

Absolutely.

> However, a `$HOME/.rustfmt.toml` is already found by `rustfmt` in many cases, since most source files are probably found somewhere in the user's home directory. Maybe somebody has a use case for applying a rustfmt configuration for things inside `$HOME`, but not outside of it.

I am not seeing how someone might be using it inside their home directory nowadays. 

> So we'd be _changing_ the meaning of a `$HOME/.rustfmt.toml` from "config for everything under your home dir" to "config for everything". (I don't expect anyone to have any source code in `$XDG_CONFIG_HOME/rustfmt` ;) ).

Neither on `$HOME`. `$HOME/foo`, for sure.

> Anyway, if we do it, `$XDG_CONFIG_HOME/rustfmt/rustfmt.toml` should probably be looked for only _after_ looking for a global `$HOME/.rustfmt.toml`, because otherwise things would get inconsistent: `$HOME/projects/foo/` would use the latter, and `/tmp/projects/foo` would use the former.

Sure. It should respect this order.

**Comment by m-ou-se** [comment]
Cool. Updated the code!

**Comment by otavio** [comment]
Please rebase this branch since it does not apply anymore.

**Comment by m-ou-se** [comment]
Rebased.

**Comment by topecongiro** [comment]
@m-ou-se Thank you for your contribution to rustfmt!

However I am not sure whether this feature is that useful. AFAICT most Rust projects do not have rustfmt.toml, so having a global rustfmt.toml makes working on multiple projects difficult, as it overwrites the default settings in most projects. What kind of use cases are in your mind? Is having rustfmt.toml on your home directory not enough?

**Comment by m-ou-se** [comment]
A `rustfmt.toml` in my home directory is (right now) a 'mostly global' configuration. If people are using that (which they are), why not make it work properly by making it the actual global config?

I often make little experiments in Rust, often in /tmp, sometimes in /home, where I want to use rustfmt with my default settings right away. So far every project that I worked on that uses rustfmt has had a `rustfmt.toml`. If they don't have it, I usually just don't use rustfmt, but just format by hand to match the rest of the code.

**Comment by topecongiro** [comment]
@m-ou-se My apologies for the delay, and thank you for the explanation! Sounds fair enough.

**Comment by topecongiro** [comment]
@m-ou-se Sorry, could you please resolve the conflicts?

**Comment by m-ou-se** [comment]
Done. Travis is reporting a few failures, but they seem unrelated to this PR, as the current master has the same failures.

**Comment by topecongiro** [comment]
Thank you!

**Pull request merged**
