### PR TITLE
subtree-push nightly-2024-04-08

### PR DESCRIPTION
**Pull request by ytmimi**
Bumping the toolchain version as part of a git subtree push

current toolchain (nightly-2023-12-28):
  - 1.77.0-nightly (89e2160c4 2023-12-27)

latest toolchain (nightly-2024-04-08):
  - 1.79.0-nightly (9d5cdf75a 2024-04-07)

r? @calebcartwright

### CODE REVIEW

**Comment by ytmimi** [comment]
@calebcartwright I think we need to remove or disable the [`generic-simd`](https://github.com/rust-lang/rustfmt/blob/728939191e4218e2c1296c7ba3eb36590cbcb9bd/Cargo.toml#L33) feature. [bytecount](https://github.com/llogiq/bytecount) uses [packed_simd](https://github.com/rust-lang/packed_simd), which is where the [error is occurring](https://github.com/rust-lang/packed_simd/issues/360) on our nightly builds.

**Comment by calebcartwright** [comment]
> @calebcartwright I think we need to remove or disable the [`generic-simd`](https://github.com/rust-lang/rustfmt/blob/728939191e4218e2c1296c7ba3eb36590cbcb9bd/Cargo.toml#L33) feature. [bytecount](https://github.com/llogiq/bytecount) uses [packed_simd](https://github.com/rust-lang/packed_simd), which is where the [error is occurring](https://github.com/rust-lang/packed_simd/issues/360) on our nightly builds.

I see you're working on getting that fixed upstream, happy to consider alternatives in parallel (e.g. adjusting feature specification on our end)

**Comment by ytmimi** [comment]
Yeah, I thought I'd take a stab at resolving the issue in https://github.com/llogiq/bytecount/pull/92. CI is passing so I'm guessing I ported things over from `packed_simd` to `std::simd` correctly. Depending on how urgently we want to get the sync in I think we have 3 options:

1. Wait for the fix to be released upstream
2. Temporarily vendor the changes locally so we can still offer the `generic-simd` feature
3. (Temporarily) drop the `generic-simd` feature.

Let me know if anything else comes to mind or if you'd prefer to move forward with one of these options.

**Comment by calebcartwright** [comment]
I don't think there's any particular urgency to push a sync through at the moment. It's been too long since the last one, but that was the case last week and that will remain the case next week.

As such I'd rather take a pause and seek a resolution to the root cause as opposed to trying to work around symptoms

**Comment by ytmimi** [comment]
Works for me. Hopefully the `bytecount` maintainers can help get the upstream PR reviewed soon🤞🏼

**Comment by ytmimi** [comment]
@calebcartwright `bytecount` pushed a new minor release with fixes for `generic-simd` 🎉

**Comment by ytmimi** [comment]
@calebcartwright is it fine to remove [`error-chain`](https://github.com/rust-lang-deprecated/error-chain) from our integration tests? The project is no longer maintained.

**Comment by calebcartwright** [comment]
> @calebcartwright is it fine to remove [`error-chain`](https://github.com/rust-lang-deprecated/error-chain) from our integration tests? The project is archived and it seems that the tests don't build anymore with the nightly version we're bumping to.

If the project is archived then yes, though would you mind sharing some more details about you mean regarding the tests not building?

**Comment by ytmimi** [comment]
> > @calebcartwright is it fine to remove [`error-chain`](https://github.com/rust-lang-deprecated/error-chain) from our integration tests? The project is archived and it seems that the tests don't build anymore with the nightly version we're bumping to.
> 
> If the project is archived then yes, though would you mind sharing some more details about you mean regarding the tests not building?

If you take a look at [integration.sh](https://github.com/rust-lang/rustfmt/blob/master/ci/integration.sh), we start by reformatting the crate:
https://github.com/rust-lang/rustfmt/blob/c97996fab61fc09432abcf64dbe3ce2d84f4d679/ci/integration.sh#L21

And then we clone the repo, and build and run the test suite for that crate to make sure that the code still builds after formatting. It's when we try to build the tests that things fail:
https://github.com/rust-lang/rustfmt/blob/c97996fab61fc09432abcf64dbe3ce2d84f4d679/ci/integration.sh#L107-L114

You can confirm the failure by cloning the repo and trying to run the tests with the nighty version that we're bumping to:
Screen Shot 2024-06-04 at 2 23 45 PM


And yeah, the repo is archived
Screen Shot 2024-06-04 at 2 18 05 PM

**Comment by ytmimi** [comment]
closing in favor of #6188

**Pull request closed without merging**
