### PR TITLE
Fix overriding license header bug

### PR DESCRIPTION
**Pull request by cmichi**
Closes https://github.com/rust-lang/rustfmt/issues/4487.

### CODE REVIEW

**Comment by calebcartwright** [comment]
LGTM! Would you mind adding a test case to prevent any future regressions?

This would probably be a good place to put it:
https://github.com/rust-lang/rustfmt/blob/cbe01e47024c852e2ed852671e76f7929c4bab91/src/config.rs#L547-L562

Using a toml config that sets some value (doesn't really matter what) and then overriding the value with an empty string (this is what the cli override uses) and asserting it's none should suffice. Here's two example tests that respectively each do one of those for reference

https://github.com/rust-lang/rustfmt/blob/cbe01e47024c852e2ed852671e76f7929c4bab91/src/config.rs#L976-L990

**Comment by calebcartwright** [comment]
Sorry I forgot to mention, add this to the test
```rust
if !is_nightly_channel!() {
    // This test requires nightly
    return;
}
```

**Comment by cmichi** [comment]
@calebcartwright Thanks, I think the windows tests are failing due to network latency, could you restart them please?

And if you would be so kind, do you have any idea when this will land in a published release?

**Review by calebcartwright — APPROVED** [review]
Thanks!

**Comment by calebcartwright** [comment]
> And if you would be so kind, do you have any idea when this will land in a published release?

Planning to backport this into the upcoming 1.4.23 release, but no date yet on when that'll hit nightly

**Pull request merged**
