### PR TITLE
Backport 3795

### LINKED ISSUE #5362: Rustfmt wrongly alphabatizes raw identifiers in `use` statements
# Description

I'm writing a toy compiler, and recently split up the elements of my grammar into their own modules.
Unfortunately, there's overlap between the elements and some Rust keywords, so sometimes I need to use raw identifiers:
```
use self::r#enum::*;
use self::interface::*;
use self::struct::*;
```
I would expect these to be sorted alphabetically, _not including the `r#`_
But, rustfmt seems to include it when sorting, and changes this to:
```
use self::interface::*;
use self::r#enum::*;
use self::struct::*;
```

Note that this _doesn't_ happen with modules:
```
mod r#enum;
mod interface;
mod struct;
```
here rustfmt correctly ignores the `r#` prefix when sorting.

I'm open to fixing this, if someone could point me in the right direction! Since it *seems* \*crosses fingers\* like an easy fix.

# Environment

rustfmt 1.4.38-nightly (e0944922 2022-05-31) on macOS Monterey

### PR DESCRIPTION
**Pull request by ytmimi**
Backport and version gate the original fix for use statement sorting with raw identifiers (#3795)

Let me know if any additional tests need to be added to this.

Closes #5362

### CODE REVIEW

**Comment by ytmimi** [comment]
It seems the integration tests are failing because of issues related to https://github.com/clap-rs/clap/issues/3822

**Comment by ytmimi** [comment]
So I think the issue is two fold. I believe we're running into an issue with [cargo install --path . --force](https://github.com/rust-lang/rustfmt/blob/7b73b60faca71d01d900e49831fcb84553e93019/ci/integration.sh#L18) installing a newer version of clap than we have listed in our `Cargo.toml` and then we're hitting the deprecation warning. We're using [clap==3.1](https://github.com/rust-lang/rustfmt/blob/7b73b60faca71d01d900e49831fcb84553e93019/Cargo.toml#L40). Here's a snippet from the help docs for `cargo help install`:


>By default, the Cargo.lock file that is included with the package will be ignored. This means that Cargo will recompute
which versions of dependencies to use, possibly using newer versions that have been released since the package was
published. The --locked flag can be used to force Cargo to use the packaged Cargo.lock file if it is available. This may be useful for ensuring reproducible builds, to use the exact same set of dependencies that were available when the package was published. It may also be useful if a newer version of a dependency is published that no longer builds on your system, or has other problems. The downside to using --locked is that you will not receive any fixes or updates to any dependency. Note that Cargo did not start publishing Cargo.lock files until version 1.37, which means packages published with prior versions will not have a Cargo.lock file available.

And here's a snippet from the `bitflags` integration test when running `cargo install --path . --force`:

>  **Downloaded clap v3.2.1**
  Downloaded serde_derive v1.0.137
  Downloaded itertools v0.10.3
  Downloaded heck v0.4.0
  Downloaded unicode-segmentation v1.9.0
  Downloaded memchr v2.5.0
  Downloaded thiserror v1.0.31
  Downloaded serde_json v1.0.81
  Downloaded bstr v0.2.17
  Downloaded itoa v1.0.2
  Downloaded cargo-platform v0.1.2
  Downloaded serde v1.0.137
  Downloaded anyhow v1.0.57
  Downloaded rustc-workspace-hack v1.0.0
  Downloaded log v0.4.17
  Downloaded proc-macro2 v1.0.39
  Downloaded quote v1.0.18
  Downloaded os_str_bytes v6.1.0
  Downloaded globset v0.4.9
  Downloaded env_logger v0.9.0
  Downloaded atty v0.2.14
  Downloaded dirs-next v2.0.0
  **Downloaded clap_derive v3.2.1**

Based on the help text it seems like the remedy is to add the `--locked` flag

**Comment by ytmimi** [comment]
On a side note if you take a look at one of the integration tests that passed (clippy) for example
(export logs for future viewing [logs_6801.zip](https://github.com/rust-lang/rustfmt/files/8893149/logs_6801.zip) You'll notice that it was reported as a success, but the test actually failed. Not sure if this is a problem with the `ci/integration.sh` script of with GitHub Acitions.
Screen Shot 2022-06-13 at 1 14 40 PM
)

**Comment by calebcartwright** [comment]
> On a side note if you take a look at one of the integration tests that passed (clippy) for example
(exported logs for future viewing -> [logs_6801.zip](https://github.com/rust-lang/rustfmt/files/8893149/logs_6801.zip)), you'll notice that it was reported as a success, but the test actually failed.

This is intentional, but in my opinion is more reflective of the limited utility these tests really provide. See below for more details

https://github.com/rust-lang/rustfmt/blob/7b73b60faca71d01d900e49831fcb84553e93019/.github/workflows/integration.yml#L33-L38
https://github.com/rust-lang/rustfmt/blob/7b73b60faca71d01d900e49831fcb84553e93019/.github/workflows/integration.yml#L55-L56

**Comment by ytmimi** [comment]
Ahh I see. Thanks for pointing that out!

**Review by calebcartwright — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
