### PR TITLE
Clarify generated marker requires a config option

### PR DESCRIPTION
**Pull request by stepancheg**

### CODE REVIEW

**Comment by ytmimi** [comment]
Thanks for submitting this PR. I think the additional context in the CHANGELOG is helpful!

I wasn't too familiar with the ``format_generated_files`` configuration option so I went and checked our [configuration documentation](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#format_generated_files). Looks like we don't have any examples listed there. Would it be possible to add an example of code that gets formatted when ``format_generated_files=true`` and an example where code is left unformatted when ``format_generated_files=false``?

I figure if we're taking the time to update the CHANGELOG we should also clarify things in the configuration docs.

**Comment by stepancheg** [comment]
Tests fail. Looking.

**Comment by ytmimi** [comment]
Got it. Just out of curiosity, what were the examples that you tried to add that caused tests to fail?

**Comment by stepancheg** [comment]
See the previous version of this PR: https://github.com/rust-lang/rustfmt/commit/c70b5b483975bcbf7740e05f73b24beded10b951

**Comment by ytmimi** [comment]
Thanks for pointing that out. I think we can move forward with this and we can add those examples when we work through the FIXME

**Review by ytmimi — APPROVED** [review]

**Review by calebcartwright — APPROVED** [review]
Thank you!

**Pull request merged**
