### PR TITLE
Issue #4059 - comments handling before and after long attrs or list

### PR DESCRIPTION
**Pull request by davidBar-On**
Resolve issue #4059  formatting when comments are before/after long attribute or at the end of long list or list, like:

`fn a1 /* comment */ (#[aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa] a: u8) {}`
`fn a1(#[aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa] /* comment */ a: u8) {}`

Also partly fixed following example.  Will be fully fixed with #2896 resolution:

```
fn main() {
use crate::formatting::{
    comment::{collect_comment_contents, combine_strs_with_missing_comments, rewrite_comment
	},/* COMMENT <<<<*/
}; }
```

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thank you for the PR! This has caused quite a lot of test failures, could you please take a look and adjust the proposed changes accordingly?

Also, we really shouldn't be moving comments down to a separate line, especially when there's no need to; the inline comments in these cases are associated with the line they are on, and moving them won't be strictly semantic preserving.

Lastly, please also add some [test cases](https://github.com/rust-lang/rustfmt/blob/master/Contributing.md#creating-test-cases) that cover the referenced issues.

**Comment by davidBar-On** [comment]
Hopefully the issue was fixed.  It was related to extra whitespace that were at the end of the line when comment was moved to new line.  There are still some test errors, but none seem to be related to the changes I made (most of them are because of `tests/parser/issue-4126/invalid.rs`).

I don't understand the comment about "we really shouldn't be moving comments down to a separate line".  This is done when line width is not large enough to include the comment.

I will add related tests.

**Comment by calebcartwright** [comment]
> I don't understand the comment about "we really shouldn't be moving comments down to a separate line". This is done when line width is not large enough to include the comment.

If you look at the results from the failing tests, you can see that's not the case. The proposed changes in this PR are causing all sorts of comments to be moved down when they absolutely should not be moved. For example:
```
Mismatch at tests/source/enum.rs:68:
-    SkippedItem(String,String,), // Post-comment
+    SkippedItem(String,String,),
+    // Post-comment
     #[another_attr]
     #[attr2]
     ItemStruct {
```

**Comment by davidBar-On** [comment]
OK. Thanks. I now see the problem (I have to learn how to better look at the tests results).  Will evaluate.

**Comment by calebcartwright** [comment]
> OK. Thanks. I now see the problem (I have to learn how to better look at the tests results).

No worries! The output from test failures is probably most easily viewed in your local terminal, but you can also see them (albeit without colorized diffs) in the CI logs https://github.com/rust-lang/rustfmt/pull/4390/checks?check_run_id=1008055033

**Pull request closed without merging**
