### PR TITLE
1.x: Bump rustc-ap to v679

### PR DESCRIPTION
**Pull request by dtolnay**
This is a backport of https://github.com/rust-lang/rustfmt/pull/4423 and https://github.com/rust-lang/rustfmt/pull/4433.

### CODE REVIEW

**Review by calebcartwright — APPROVED** [review]
Thanks! Will merge this once the PR checks finish but probably still a little ways out from pushing v1.4.22 to nightly. Is this something needed urgently in rustfmt 1.x release?

**Comment by dtolnay** [comment]
I just want to be sure that `unsafe mod` works with the rustfmt that ships with the rustc release which first supports it. Otherwise it would block me from being able to require the syntax in code downstream of https://github.com/dtolnay/cxx for an unnecessary additional release cycle.

**Comment by calebcartwright** [comment]
> I just want to be sure that `unsafe mod` works with the rustfmt that ships with the rustc release which first supports it.

Gotcha. I'll go ahead and start the process in that case, although as you may already know, rustc-ap bumps have to be coordinated and sequenced across several different repos (racer and RLS as well as here) so can't necessarily make any guarantees

**Comment by calebcartwright** [comment]
Now that the corresponding version of racer has been released I'll run our release here and open a PR in RLS

**Pull request merged**
