### PR TITLE
itertools bump to 0.12

### PR DESCRIPTION
**Pull request by klensy**
changelog: https://github.com/rust-itertools/itertools/blob/v0.12.1/CHANGELOG.md

### CODE REVIEW

**Comment by ytmimi** [comment]
@klensy thanks for the PR. I took a really quick look at the changelog (thanks for the link), and I'll review it more thoroughly when I've got some time, but I wanted to ask you if you think there are any breaking changes in the `0.12` release that you think would impact rustfmt?

**Comment by klensy** [comment]
Don't think so: mentioned breaking changes in changelog should give compile errors if unfixed.

**Comment by ytmimi** [comment]
> Don't think so: mentioned breaking changes in changelog should give compile errors if unfixed.

Okay. I'm mostly wondering if there are any changes in behavior that wouldn't be caught at compile time.

**Review by ytmimi — APPROVED** [review]
Finally got around to reviewing the [v0.12 changelog](https://github.com/rust-itertools/itertools/blob/v0.12.1/CHANGELOG.md#0120), and I agree that there don't seem to be any breaking changes that would impact rustfmt.

**Pull request merged**
