### PR TITLE
Recover comments in return type

### LINKED ISSUE #5870: rustfmt eats comment in return type with unnecessary parenthesis
This code:
```rust
fn f() -> (/* is something */ bool) {}
```
Turns into this:
```rust
fn f() -> (bool) {}
```
Not too big of a deal as this isn't a tuple (due to the missing `,`) and doesn't happen with tuples, but it should probably look for a comment here so it's retained after the programmer adds the `,` (and presumably other types, too)

Doesn't seem to happen in other places (like the type annotation for a local).

### LINKED ISSUE #5874: rustfmt eats comment after `->` in return type
```rust
fn a() -> /* my super detailed comment on what this bool is */ bool {}
```
The comment is entirely eaten:
```rust
fn a() -> bool {}
```

### PR DESCRIPTION
**Pull request by Centri3**
Fixes #5870
Fixes #5874

May need a bit DRYness.

### CODE REVIEW

**Comment by ytmimi** [comment]
@Centri3 Thanks again for another PR. Can you close this one and open up two separate PRs that fixe each issue independently.

1) Each fix will be easier to review if the PRs are more focused. 
2) Although rustfmt drops comments in both cases, the underlying issues are unrelated.
3) All the test cases you've presented use small, single line block comments, but rustfmt will need to handle edge cases with long, multi line block comments and line comments when it starts recovering comments in those positions. It'll probably be easier to work through those cases if these are broken up.
4) I don't want one of these issues to stall waiting for the completion of the other.

**Comment by Centri3** [comment]
Sure thing, I'll do that once I get the chance

**Comment by ytmimi** [comment]
Great! No rush on this!

**Comment by ytmimi** [comment]
Close this one now as the ask was to open two separate PRs. Just trying to clean up the backlog a little.

**Pull request closed without merging**
