### PR TITLE
Stabilize disable_all_formatting

### PR DESCRIPTION
**Pull request by rchaser53**
related: https://github.com/rust-lang/rustfmt/issues/3197, https://github.com/rust-lang/rustfmt/issues/3388

This options is a very simple and no bugs are reported.
So I think this options can be stabilized only tests addition.

### CODE REVIEW

**Comment by topecongiro** [comment]
I would rather deprecate `disable_all_formatting` rather than stabilize it as we have `ignore` which is more flexible.

**Comment by rchaser53** [comment]
I also think ```ignore``` is better than ```disable_all_formatting```.
A good ```disable_all_formatting's``` points better than ```ignore``` is that can ignore every file.
But we can do same thing without ```disable_all_formatting``` option. ```Do not use rustfmt.```
Should I change the PR ```Stabilize disable_all_formatting ``` to ```Deprecate disable_all_formatting```?

cc: @nrc @scampi

**Comment by topecongiro** [comment]
Originally `disable_all_formatting` was added to work around a not-so-good integration between an editor and rustfmt (cc https://github.com/rust-lang/rustfmt/pull/1297). I think the option is useful in that respect.

Other than replacing `disable_all_formatting`, `ignore` is useful when you have submodules in your crate that you do not want rustfmt to touch. A canonical example https://github.com/rust-lang/rust.

> Should I change the PR Stabilize disable_all_formatting to Deprecate disable_all_formatting?

Before deprecating `disable_all_formatting`, I prefer to stabilize `ignore` first. It is blocked by #3413, but currently I do not have time to work on it. @rchaser53 If you want to push this further, it would be awesome if you could take it over and implement the feature (and add some tests, if possible)!

**Comment by rchaser53** [comment]
I understand the context of disable_all_formatting.
Ok. I take #3413 over.

**Comment by topecongiro** [comment]
@rchaser53 Thanks!

**Comment by topecongiro** [comment]
Closing this as `disable_all_formatting` should be deprecated in favor of `ignore` (see https://github.com/rust-lang/rustfmt/pull/3481#issuecomment-478306223). @rchaser53 thank you for all the work (including many other PRs to rustfmt)!

**Comment by Stargateur** [comment]
> Warning: can't set `ignore = IgnoreList { path_set: {"/"}, rustfmt_toml_path: "" }`, unstable features are only available in nightly channel.

This should be an error - -, this was really unexpected that it format anyway !

**Pull request closed without merging**
