### PR TITLE
subtree-push nightly-2024-06-07

### PR DESCRIPTION
**Pull request by ytmimi**
Bumping the toolchain version as part of a git subtree push

current toolchain (nightly-2023-12-28):

* 1.77.0-nightly (89e2160c4 2023-12-27)

latest toolchain (nightly-2024-06-07):

* 1.80.0-nightly (98489f248 2024-06-06)

r? @calebcartwright

### CODE REVIEW

**Comment by ytmimi** [comment]
[Diff-Check Job](https://github.com/rust-lang/rustfmt/actions/runs/9411194756)

**Comment by calebcartwright** [comment]
There's a lot of churn in that check (i'm so glad we have this check!). Do you have any thoughts on cause?

**Comment by ytmimi** [comment]
Some of it might just be false positives. I'll probably need to run things manually to confirm, but there were some issues recently where the job was just randomly failing  when run against the `r-l/rust` repo (https://github.com/rust-lang/rustfmt/pull/6154#issuecomment-2121482294). I think it might have something to do with what was being [discussed here on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/.60x.20fmt.60.20not.20formatting.20unchanged.20files), though I'm not 100% sure.

**Comment by ytmimi** [comment]
To double check that these aren't weird false positives I'm running the [Diff-Check Job using my forks HEAD branch which is up to date with `r-l/rustfmt`](https://github.com/rust-lang/rustfmt/actions/runs/9432029308/job/25981305438)

**Comment by ytmimi** [comment]
[re-running the Diff-Check job on this PR to double check these changes](https://github.com/rust-lang/rustfmt/actions/runs/9432112184/job/25981485702). If the job fails again then I'll be fairly certain these aren't false positives. Next thing I'd want to look into when the job fails is if `version=One` formatting is consistent. It might just be the case that `version=Two` formatting is different.

**Comment by ytmimi** [comment]
Alright, so I investigated things locally and made sure to run both binaries with `version=One`. The results were similar to what we've been seeing. These are the files in `r-l/rust` that I'll need to take a closer look at:

* `src/tools/rust-analyzer/crates/parser/test_data/parser/ok/0070_expr_attr_placement.rs`
  * Likely related to the `Disallow ambiguous attributes on expression` PRs that I describe in the last bullet. 
* `src/tools/rustfmt/tests/source/postfix-match/pf-match.rs`
  * Add in https://github.com/rust-lang/rust/pull/121619. Likely that the older rustfmt doesn't understand the new syntax gated by `#![feature(postfix_match)]`. 
* `src/tools/rustfmt/tests/source/mut_ref.rs`
  * Added in https://github.com/rust-lang/rust/pull/123080. Likely that the older rustfmt doesn't understand the new syntax gated by `#![feature(mut_ref)]`.
* `src/tools/rustfmt/tests/source/macros/rewrite-const-item.rs`
  * Fix for [#6035](https://github.com/rust-lang/rustfmt/issues/6035) Added in [rust-lang/rust#120218](https://github.com/rust-lang/rust/pull/120218), which resolved a regression introduced by `nightly-2023-12-28`. This has been out on nightly since `nightly-2024-01-23`.
* `src/tools/rustfmt/tests/source/attrib.rs`
  * I'm personally surprised to see this `source` test in rustfmt report errors because our CI passed indicating that the `target` file is formatted correctly 
  * The only change I can find to this file is https://github.com/rust-lang/rust/pull/124099. It looks like this change was reverted due to a beta regression in https://github.com/rust-lang/rust/pull/126101, so we should probably bump to a nightly version that includes that reverted commit. Maybe that will resolve some of these issues.

**Comment by ytmimi** [comment]
closing this in favor of https://github.com/rust-lang/rustfmt/pull/6193. It pulls in an additional commit from `r-l/rust` that seems to have resolved the attribute formatting issues.

**Pull request closed without merging**
