### PR TITLE
fix Inconsistency between  loop  and while

### PR DESCRIPTION
**Pull request by rchaser53**
related: https://github.com/rust-lang/rustfmt/issues/3227

### CODE REVIEW

**Comment by rchaser53** [comment]
Oh sorry. I forgot to add version-gate.

**Comment by otavio** [comment]
The change and test looks perfect, the only rework would be a more descriptive commit log. What about:

```
version/2: Align loop and while formatting

The loop and while formatting was diverting as  `loop` 
was not being moved to a new, indented block, as `while`
was.

This commit fixes this inconsistency but pins it to version 2
to avoid changing existing code.
```

Something on this line ...

**Comment by rchaser53** [comment]
Thank you for the review.
Is this change ok? @scampi

**Comment by rchaser53** [comment]
I see. I removed source and target one.rs.

**Comment by scampi** [comment]
@rchaser53 Sorry if I was not clear:

- you can remove `tests/source/issue-3227/one.rs`
- you keep `tests/target/issue-3227/one.rs`

The test is good because it checks the formatting when the version is `One`. What I meant is that the the source file, i.e., `tests/source/issue-3227/one.rs`, is not needed since the target file is the same.
If you keep only `tests/target/issue-3227/one.rs` then it will be an indempotence test and that's perfect.

**Comment by rchaser53** [comment]
Oh, sorry for many times. I rebased it.

**Comment by scampi** [comment]
looking good, build failures unrelated to the PR.

**Pull request merged**
