### PR TITLE
recognize strings inside comments in order to avoid indenting them

### LINKED ISSUE #3270: modifies commented out multiline string literals
I can have code like this
````rust
    let s = String::from(
        "
hello
world
",
    );

    assert_eq!(s, "\nhello\nworld\n");
````
and comment out the string
````rust
pub fn main() {
 /*   let s = String::from(
        "
hello
world
",
    ); */

    assert_eq!(s, "\nhello\nworld\n");
}
````

when I now rustfmt, rustfmt changes the indent of the comments  but it does not see that by indenting the code of the literal, it actually changes the literal.
````rust
pub fn main() {
    /*   let s = String::from(
            "
    hello
    world
    ",
        ); */

    assert_eq!(s, "\nhello\nworld\n");
 }
````
If I now remove the comment markers, the assertion will no longer hold.

### PR DESCRIPTION
**Pull request by scampi**
Close #3270

### CODE REVIEW

**Comment by scampi** [comment]
@matthiaskrgr Can you try this branch to check if it fixes your problem ?

**Comment by matthiaskrgr** [comment]
Looks good to me. Thank you!

**Comment by scampi** [comment]
The build with the error below so I restarted it:

```
The command "curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y" failed and exited with 1 during .
```

Now `futures-rs` doesn't compile with errors like:

```
error[E0308]: mismatched types
   --> futures-util/src/future/maybe_done.rs:110:18
    |
110 |         Pin::set(self, MaybeDone::Done(res));
    |                  ^^^^
    |                  |
    |                  expected mutable reference, found struct `std::pin::Pin`
    |                  help: consider mutably borrowing here: `&mut self`
    |
    = note: expected type `&mut std::pin::Pin<_>`
               found type `std::pin::Pin<&mut future::maybe_done::MaybeDone<Fut>>`
```

The crate `packed_simd` timed out while compiling.

Both failures occurred before `rustfmt` ran.

**Comment by topecongiro** [comment]
This PR changes the default formatting, but only for comment. Does the RFC requires us to to guard this by version as well? cc @nrc

**Comment by nrc** [comment]
> This PR changes the default formatting, but only for comment

Yes. Any change to how a file is formatted must be behind either a version flag or a non-default feature flag. The reasoning is that if a project has been formatted using v1.0 and there CI enforces formatting, then upgrading to v1.1 in their CI should not cause CI to fail.

**Comment by scampi** [comment]
I will fix and it makes sense @nrc 
Thanks @topecongiro

**Comment by nrc** [comment]
Thanks!

**Pull request merged**
