### PR TITLE
subtree-push 2024-06-24

### PR DESCRIPTION
**Pull request by compiler-errors**
Bumped the toolchain from rust-lang/rust@8337ba918 2024-06-12 to rust-lang/rust@6b0f4b5ec 2024-06-24.

Pulled in some interesting commits, notably:
* https://github.com/rust-lang/rust/pull/126888 hotfix for a stray println.
* https://github.com/rust-lang/rust/pull/126754 which implements the style consensus in https://github.com/rust-lang/rust/pull/126753.

Otherwise a pretty minor subtree sync :^)

### CODE REVIEW

**Comment by ytmimi** [comment]
weird, I see that https://github.com/rust-lang/rustfmt/pull/6217/commits/514fe39e250569a3c894c116a8abe95f635fef1f pulled in the commit that removed the stray `println!`, but when I look at all the changed files in the GitHub UI I'm not seeing the change.

**Comment by compiler-errors** [comment]
Oh yea, what the heck? The merge commit added it back.

**Comment by ytmimi** [comment]
Really strange behavior. Maybe you could reset to 514fe39 and then try the merge again?

**Comment by compiler-errors** [comment]
Yep -- I did that. I think this is just what git thinks is right when merging `origin/master` *into* `sync-from-rust-2024-06-24`.

**Comment by compiler-errors** [comment]
I believe this is relevant:

> With the strategies that use 3-way merge (including the default, ort), if a change is made on both branches, but later reverted on one of the branches, that change will be present in the merged result; some people find this behavior confusing. It occurs because only the heads and the merge base are considered when performing a merge, not the individual commits. The merge algorithm therefore considers the reverted change as no change at all, and substitutes the changed version instead.

**Comment by compiler-errors** [comment]
I'll push a commit on top to revert the bad merge tomorrow. Git is so weird.

**Comment by calebcartwright** [comment]
> Git is so weird.

it really can be. it's times like these that make me feel like I need to review every line of diffs on the pushes, even the "successfully" staged ones

**Comment by compiler-errors** [comment]
@calebcartwright: I believe it's probably most effective to add as a "step" to your runbook (in your brain or otherwise) to review the diff of the merge commit itself, rather than reviewing every line which can be a lot of work.

You can view the diff of the merge commit if you ask git to show it:

> There are no new changes to show, but you can still [view the diff.](https://github.com/rust-lang/rustfmt/commit/b5fa338f23015c87c670b450d453c070fc1df052)

I would've probably caught that if I knew that this was something git could do.

**Review by calebcartwright — APPROVED** [review]

**Pull request merged**
