### PR TITLE
Improve formatting of empty macro_rules! definitions

### LINKED ISSUE #5882: rustfmt adds trailing spaces to macro rules
```rust
macro_rules! foo {}
foo::bar!();
```
rustfmt --check
```
Diff in /home/matthias/vcs/github/rust/src/tools/rust-analyzer/crates/parser/test_data/parser/inline/ok/0062_mod_contents.rs at line 1:
-macro_rules! foo {}
+macro_rules! foo {
+
+}
 foo::bar!();

error[internal]: left behind trailing whitespace
 --> /home/matthias/vcs/github/rust/src/tools/rust-analyzer/crates/parser/test_data/parser/inline/ok/0062_mod_contents.rs:2:2:1
  |
2 |
  | ^^^^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

`rustfmt 1.6.0-nightly (f88a8b7 2023-08-08)`

### PR DESCRIPTION
**Pull request by ytmimi**
Fixes #5882

### CODE REVIEW

**Comment by calebcartwright** [comment]
Haven't looked at code and understand the respective issues differ in defs vs calls, but any overlap/correlation between this and ##5879?

**Comment by ytmimi** [comment]
From what I can tell the two issues don't seem to be related. 

#5882 is an odd case where a `macro_rules!` definition doesn't have any arms. The code in `rewrite_macro_def` assumes that there will be arms and always adds an indented newline for the first arm even if it's not there. This PR looks to fix the `left behind trailing whitespace` issue.

The approach in this PR is to treat the empty macro body as a dummy block and take advantage of comment recovery code defined in the  `rewrite_block` code path.

#5879 on the other hand is highlighting an issue with how rustfmt rewrites `vec!{}` calls. rustfmt makes the assumption that `vec!` will always be written with `[ ]` delimiters, and that leads to a panic! when that assumption isn't ture.

**Review by calebcartwright — APPROVED** [review]
lgtm thanks!

(also noticed that this fixes an issue where if the def was solely comments/whitespace then rustfmt would simply erase the comments, might be worth checking to see if there's any open issues to that effect which we could also close as part of this)

**Comment by ytmimi** [comment]
Doing a search for `macro_rules!` in the issue tracker didn't turn up any issues with empty `macro_rules!` macros.

**Pull request merged**
