### PR TITLE
Add more tests for comments in lists

### LINKED ISSUE #4430: Line comments turned into block comments despite `normalize_comments`
**Input & expected output**

```rust
fn main() {
    match a {
        b => c,
        // b => c,
        // b => c,
    }
}
```

**Output**

```rust
fn main() {
    match a {
        b => c,
        /* b => c,
         * b => c, */
    }
}
```

**Config**
```toml
imports_layout = "HorizontalVertical"
max_width = 80
normalize_comments = true
match_arm_blocks = false
wrap_comments = true
blank_lines_upper_bound = 2
merge_imports = true
report_fixme = "Always"
report_todo = "Always"
use_field_init_shorthand = true
reorder_impl_items = true
```

Unfortunately I can't reproduce it in the playground.

EDIT: changed the example code

- rustfmt version: `rustfmt 1.4.21-nightly (01f2eadc 2020-09-04)`
- From where did you install rustfmt?: **rustup**

### PR DESCRIPTION
**Pull request by mujpao**
Fixes #4430 and #4420

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thanks! However, it'd be better to move the test files to a different, respective directories given that none of those files are directly associated with the current subdirectory (`issue-4909`) they're currently being proposed under

**Comment by mujpao** [comment]
Do you mean that I should make a separate file or directory for each issue, or should I just rename the `issue-4909` directory to `comments-in-lists` or something like that?

**Comment by calebcartwright** [comment]
> Do you mean that I should make a separate file or directory for each issue, or should I just rename the `issue-4909` directory to `comments-in-lists` or something like that?

I think either of those will be fine. It's just that when we associate cases to specific issues we want to make sure the relationship is clear, and that's typically done via the file names, or directory names, or inline comments with issue references/links in larger/more general files

**Comment by mujpao** [comment]
Is this right? I renamed the directory and added comments for each issue.

**Comment by ytmimi** [comment]
Hey @mujpao, thanks for taking the time to rename those files. I personally think that the directory should either be named ``issue-4430`` or ``issue-4420`` to more directly associate these tests with the respective issues that this PR Fixes. Does this PR also solve [4909](https://github.com/rust-lang/rustfmt/issues/4909)?

**Comment by mujpao** [comment]
This PR just adds more tests. After working on #5091, I realized that #4420 and #4430 were also fixed by that PR, but I didn't think to add those specific test cases at the time. Since #4909, #4420, and #4430 were so closely related, I thought it would make the most sense to put all the associated tests in the same directory, but I could change it if needed.

**Comment by calebcartwright** [comment]
> I thought it would make the most sense to put all the associated tests in the same directory

That's reasonable and fine with me, but if we go that route then I'd like to see the containing directory renamed. I realize this may seem unnecessarily pedantic, but it's not uncommon for someone to need to go back to older issues and associated test cases so want to make sure the file and directory names don't cause any confusion.

**Comment by mujpao** [comment]
I already renamed the directory to `comments-in-lists`. Should I have renamed it to something else?

**Comment by calebcartwright** [comment]
> I already renamed the directory to `comments-in-lists`. Should I have renamed it to something else?

Ah so you did, my apologies! That'll work thanks :+1:

**Review by calebcartwright — APPROVED** [review]
:rocket:

**Pull request merged**
