### PR TITLE
Keep leading colons for global paths

### LINKED ISSUE #3241: Rustfmt removes `::` from use statements on Rust 2018 code
When transitioning to Rust 2018 edition, it becomes necessary to use `::` in use statements (e.g. `use ::actix::prelude::*`) in order to compile one's code. Unfortunately `rustfmt` removes these when formatting the code.

Although `cargo fmt` does work in these cases, many tools actually use `rustfmt` since it's easier to integrate into editors (e.g. `rust-mode` in Emacs). This makes it impossible to write 2018 code in those editors without tweaking.

### PR DESCRIPTION
**Pull request by scampi**
Close #3241

### CODE REVIEW

**Comment by scampi** [comment]
tests fail on `failure` and `rust-clippy` at compile-time, before running rustfmt.

**Comment by topecongiro** [comment]
Thanks for the PR! Could you add some test to clarify what this PR is trying to fix please? Also AFAICT even with this PR, rustfmt still removes the leading `::` when the imports are list or glob (e.g. `use ::{foo, bar};` or `use ::*;`).

**Comment by scampi** [comment]
@topecongiro Thanks for the review, please have a look again.

**Comment by topecongiro** [comment]
Thanks for the update! LGTM.

**Pull request merged**
