### PR TITLE
Use absolute_path instead of fs::canonicalize

### LINKED ISSUE #1873: Fail to format nested mod with relative path on windows
Following snippets will fail to format on windows.
```
#[path = "../mod_b.rs"]
mod b;
```
rustfmt-nightly will complain
> error: couldn't read "\\\\?\\C:\\src\\../mod_b.rs": The filename, directory name, or volume label syntax is incorrect. (os error 123)

That's because rustfmt needs to canonicalize the source file paths first to be able to compare with file_lines configuration later. It works fine on linux. But on windows, canonicalize will return a UNC path, which doesn't accept relative join any more.

/cc rust-lang/rust#42869

### PR DESCRIPTION
**Pull request by scampi**
This is a continuation of #3324:

- add a test for relative path to modules
- tested the fix proposed by @topecongiro works on a windows environment.

I think the comments regarding canonical paths by @rivy and @Xanewok can be revisited later once some fixes on rust itself are done (see list of open issues https://github.com/rust-lang/rustfmt/issues/1873#issuecomment-496308106). I'll open an issue to track this.

Close #1873

### CODE REVIEW

**Comment by rivy** [comment]
Any progress on this?
Using Windows `cargo fmt` is broken for lots of repos because of this...

refs: #1873 , #3324, #3603, #3688

**Comment by Diggsey** [comment]
Bump...

**Comment by rivy** [comment]
Ping @topecongiro @scampi , this has been languishing for almost a year.
What can we do to push it forward?
As I said before, this is the base cause of issues in lots of repos.

**Comment by calebcartwright** [comment]
At this point it might be easiest if someone wanted to grab the commits or changes and try from a new PR, especially considering all the subsequent changes

**Comment by topecongiro** [comment]
Closing in favor of #4131.

**Pull request closed without merging**
