### PR TITLE
Put empty trait braces on same line if possible

### LINKED ISSUE #5047: `empty_item_single_line` should apply to trait definitions as well
1.4.37-nightly

Using this rustfmt.toml 

```toml
brace_style = "AlwaysNextLine"
empty_item_single_line = true
```
rustfmt will format the following code like this:

```rust
fn function() {}

struct Struct {}

enum Enum {}

trait Trait
{
}

impl<T> Trait for T {}
```

This is inconsistent, and empty traits end up sticking out like a sore thumb. Intended behaviour is probably this:

```rust
fn function() {}
struct Struct {}
enum Enum {}
trait Trait {}
impl<T> Trait for T {}
```

This is important, as empty traits are often quite useful. For instance, you might want something like this:

```rust
trait Trait: Send + Clone {}
impl<T: Send + Clone> Trait for T {}
```

which will look quite ugly at the moment.

### PR DESCRIPTION
**Pull request by mujpao**
Fixes #5047.

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thanks for the PR! Haven't looked at this closely yet, but could you add another test where `empty_item_single_line` is true as well?

**Comment by mujpao** [comment]
I added some tests to `item-brace-style-always-next-line.rs`, but should I have put those in a new file instead?

**Comment by calebcartwright** [comment]
> I added some tests to `item-brace-style-always-next-line.rs`, but should I have put those in a new file instead?

Ah okay, sorry about that. I was thinking there'd be a pair file with `true` in the name, but what you've done is fine :+1:

**Review by calebcartwright — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
