### PR TITLE
Handle non-ascii character at boundary

### LINKED ISSUE #5023: Panic with `wrap_comments` and non-ascii character at comment wrap boundary
There is a piece of code in my project like:

```rust
fn main() {
    if xxx {
        let xxx = xxx
            .into_iter()
            .filter(|(xxx, xxx)| {
                if let Some(x) = Some(1) {
                    // xxxxxxxxxxxxxxxxxx, xxxxxxxxxxxx, xxxxxxxxxxxxxxxxxxxx xxx xxxxxxx, xxxxx xxx
                    // xxxxxxxxxx. xxxxxxxxxxxxxxxx，xxxxxxxxxxxxxxxxx xxx xxxxxxx
                    // 是sdfadsdfxxxxxxxxx，sdfaxxxxxx_xxxxx_masdfaonxxx，
                    if false {
                        return true;
                    }
                }
                false
            })
            .collect();
    }
}
```

When I execute `cargo fmt`, I got an error:

```
thread 'main' panicked at 'index out of bounds: the len is 48 but the index is 18446744073709551615', src/tools/rustfmt/src/string.rs:285:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The `rustfmt.toml` is the following:

```
wrap_comments = true
```

I can't understand why a few lines of comments can make fmt crash...

### PR DESCRIPTION
**Pull request by scampi**
Close #5023

### CODE REVIEW

**Comment by scampi** [comment]
With the non-ascii character at the boundary, the value of `max_width_index_in_input` is 0. The proposed fix avoids the overflow.
However, I wonder if I should instead amend the algorithm that updates `max_width_index_in_input` so that it doesn't return 0.
https://github.com/rust-lang/rustfmt/blob/76d626f5e59112adc5584ef09158c71e64b3322a/src/string.rs#L269-L280

**Comment by calebcartwright** [comment]
Yeah I was thinking that this should address the reported issue but was wondering if these types of characters appeared in different positions if it could still make us split in the wrong location.

I'd be okay moving ahead with this given the immediate relief it would provide, and consider a broader fix in a follow up PR. Happy to park on this though if you want to experiment with a different approach though

**Comment by scampi** [comment]
@calebcartwright I don't find a way to fix the computation of `max_width_index_in_input`, but I have replaced the previous with an early termination check. I think that makes the rest cleaner, knowing that `max_width_index_in_input` is at least 1.

**Review by calebcartwright — APPROVED** [review]
Agreed, seems like a reasonable approach for now and certainly addresses the pressing issue at hand :+1:

**Pull request merged**
