### PR TITLE
init: macOS apple silicon runner

### PR DESCRIPTION
**Pull request by LeviticusNelson**
I started the first steps to have aarch64-apple-darwin builds possible for rustfmt so that that people who use the aarch64-apple-darwin target can use the latest rustfmt builds.

### CODE REVIEW

**Comment by ytmimi** [comment]
Thanks for the PR, but we're going to move away from distributing pre-built binaries in the future. You can read the discussion on #5761 for more details.

The recommendation is for users to get rustfmt via rustup

```
# stable
rustup component add rustfmt

# nightly
rustup component add rustfmt --toolchain nightly
```

**Comment by LeviticusNelson** [comment]
It seems that I cannot use the nightly version of rustfmt so I just installed via homebrew
```
brew install rustfml
```

**Comment by ytmimi** [comment]
@LeviticusNelson did you mean `rustfmt` and not `rustfml`?

**Comment by LeviticusNelson** [comment]
Yes, I meant to write `rustfmt` but after figuring out how to run this tool all morning my heart was feeling the fml 😂

**Comment by ytmimi** [comment]
I'm glad that you were able to get rustfmt installed and working. I'm a bit surprised that things didn't work when you tried to install rustfmt via rustup though, and that you needed to install it via homebrew. Do you have a rust toolchain installed? If not that could be the issue.

I ask because on my mac I'm using the `nightly-aarch64-apple-darwin` toolchain and I don't have any issue running rustfmt.

**Comment by LeviticusNelson** [comment]
I was running this command while having my default set to nightly:
```
rustup component add rustfmt --toolchain nightly

# output
info: component 'rustfmt' for target 'aarch64-apple-darwin' is up to date
```
This seems to still be running the stable version of rustfmt for some reason

**Comment by ytmimi** [comment]
I'd double check whether or not you're using a nightly toolchain by default. What do you see for you `active toolchain` when you run `rustup show`?

```
active toolchain
----------------

nightly-aarch64-apple-darwin (default)
```

Assuming that your default toolchain is stable, if you just want to run nightly rustfmt on an ad hoc basis you can run `rustfmt +nightly path/to/rust_file.rs` or `cargo +nightly fmt`.

**Note: You can't pass file paths to `cargo fmt`**

You can run `rustup override nightly` to set a nightly toolchain for a specific directory, while still using a stable toolchain everywhere else. Then executing `rustfmt path/to/rust_file.rs` should get forwarded to nightly rustfmt when running in that directory. 

Alternatively, you can run `rustup default nightly` to set the default toolchain on your system to nightly. Then all calls to `rustfmt path/to/rust_file.rs` should use the nightly version, and if you want to use stable for some reason you could run `rustfmt +stable` or `cargo +stable fmt`

**Comment by LeviticusNelson** [comment]
I had to clear out `$HOME/.cargo` and reinstall rustup to get this to work properly. Thanks for the concise assistance!

**Pull request closed without merging**
