### PR TITLE
deps: bump rustc-ap crates to v686

### PR DESCRIPTION
**Pull request by ghedo**
This seems to be required to fix rustfmt build on latest nightly. See https://github.com/rust-lang/rust/issues/78341#issuecomment-716178002.

### CODE REVIEW

**Comment by ghedo** [comment]
Turns out I was a bit too optimistic... I'm going to look into what changes are required here, but if anyone has a better idea on how to make this work, feel free to take over.

**Comment by calebcartwright** [comment]
> Turns out I was a bit too optimistic... I'm going to look into what changes are required here, but if anyone has a better idea on how to make this work, feel free to take over.

:smile: Yes sometimes these are pleasantly uneventful, and other times it's a major effort to incorporate all the upstream rustc changes

**Comment by ghedo** [comment]
I think I figured it out, let's see if the builds now pass.

**Review by calebcartwright — APPROVED** [review]
Thank you!

**Pull request merged**
