### PR TITLE
Check in a rust-toolchain file

### PR DESCRIPTION
**Pull request by dtolnay**
Every time I've had to bisect something in rustfmt I've had an awful time. It involves trying to guess which nightly will build each commit based on the commit times.

By checking in a rust-toolchain file and bumping it when resolving nightly breakages, rustup is informed which nightly to go with each commit and bisects will just work.

CI will continue to build with the latest nightly always, because `override` takes priority over rust-toolchain:

https://github.com/rust-lang/rustfmt/blob/fd9e7d3e932986a49254de3a7da857a29978d3cc/.github/workflows/linux.yml#L43

### CODE REVIEW

**Comment by calebcartwright** [comment]
> Every time I've had to bisect something in rustfmt I've had an awful time. It involves trying to guess which nightly will build each commit based on the commit times.
> 
> By checking in a rust-toolchain file and bumping it when resolving nightly breakages, rustup is informed which nightly to go with each commit and bisects will just work.

Pardon the uninformed question, but is there an automated tool/process involved in that bisecting exercise?

I don't have any objections to including a toolchain file but want to make sure I understand the implications if there is such a tool. Also, I've not read up on it yet but there's apparently a new format supported for the toolchain files and not sure if that new format would provide any benefit here.

**Comment by dtolnay** [comment]
> Pardon the uninformed question, but is there an automated tool/process involved in that bisecting exercise?

Git bisect: https://git-scm.com/docs/git-bisect. Previously with manual fiddling at each commit to try to pick a toolchain that will build it. With a toolchain file, it becomes possible to use `git bisect run` fully automatedly to pinpoint a crash or change in formatting to 1 specific commit in one command:

```console
CFG_RELEASE_CHANNEL=dev CFG_RELEASE=1.48.0 git bisect run cargo run --bin rustfmt --features rustfmt -- --check repro.rs
```

Rustup will download the correct toolchain at each checkout if not already available.

<br>

> I don't have any objections to including a toolchain file but want to make sure I understand the implications if there is such a tool.

Whenever you do a build from a git checkout, it would download the correct toolchain for that build if rustup doesn't already have it.

Whoever wants to opt out can run `rustup override` to pin a different toolchain, e.g. presumably `rustup override set nightly` to get the former behavior.

<br>

> Also, I've not read up on it yet but there's apparently a new format supported for the toolchain files and not sure if that new format would provide any benefit here.

I don't think it would be applicable. It lets you set more information like what targets and what other tools like clippy to pull.

**Comment by calebcartwright** [comment]
Thanks for the info! I thought there may have been some cargo-bisect-rustc-esque tool for rustfmt I was unaware of

> Whenever you do a build from a git checkout, it would download the correct toolchain for that build if rustup doesn't already have it.

And would the absence of the rustfmt component from the default profile for the toolchain be problematic, or would `--force` be pulled in there somewhere to grab the toolchain anyway?

I ask as the vast majority of the time when we have a broken toolstate issue I won''t know the actual toolchain that will have the component/be installable without `--force` for a while afterwards

**Comment by dtolnay** [comment]
> And would the absence of the rustfmt component from the default profile for the toolchain be problematic, or would `--force` be pulled in there somewhere to grab the toolchain anyway?

Sorry, I'm not sure what you mean or what `--force` this is referring to. :confused:

Locally building rustfmt from source or running the test suite do not involve executing a rustup-managed rustfmt binary do they?

**Comment by calebcartwright** [comment]
Sorry, think I'm confusing a `rustup update ...` on an existing toolchain vs installing an explicit toolchain. In the case of the former, rustup will refuse to pull in the newer toolchain in the event the components (like rustfmt) are missing unless `--force` flag is provided, and I was wondering if it'd do something similar with a toolchain file

**Review by calebcartwright — APPROVED** [review]

**Comment by dtolnay** [comment]
To clarify what a toolchain file does:

## Before

```console
$  git checkout $arbitrary_commit
$  cargo build
...
error[E0557]: feature has been removed
  --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-686.0.0/src/lib.rs:18:12
   |
18 | #![feature(optin_builtin_traits)]
   |            ^^^^^^^^^^^^^^^^^^^^ feature has been removed
   |
   = note: renamed to `auto_traits`

error[E0658]: auto traits are experimental and possibly buggy
  --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-686.0.0/src/sync.rs:30:9
   |
30 |         pub auto trait Send {}
   |         ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #13231 <https://github.com/rust-lang/rust/issues/13231> for more information
   = help: add `#![feature(auto_traits)]` to the crate attributes to enable

error[E0658]: auto traits are experimental and possibly buggy
  --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-686.0.0/src/sync.rs:31:9
   |
31 |         pub auto trait Sync {}
   |         ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #13231 <https://github.com/rust-lang/rust/issues/13231> for more information
   = help: add `#![feature(auto_traits)]` to the crate attributes to enable

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0557, E0658.
For more information about an error, try `rustc --explain E0557`.
error: could not compile `rustc-ap-rustc_data_structures`
```

## After

```console
$  git checkout $arbitrary_commit
$  cargo build
info: syncing channel updates for 'nightly-2020-11-29-x86_64-unknown-linux-gnu'
info: latest update on 2020-11-29, rust version 1.50.0-nightly (e37f25aa3 2020-11-28)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'rust-std'
info: installing component 'rustc'
   Compiling cfg-if v0.1.10
   Compiling autocfg v1.0.0
   Compiling libc v0.2.77
... (successful build)
```

**Comment by calebcartwright** [comment]
Yup, was just playing around with it, doesn't care about missing components at all which is great. I just wanted to make sure I wouldn't need to update the file again after each nightly issue was fixed for things to work out :+1:

**Pull request merged**
