### PR TITLE
Change directory name in test_merged_config test

### LINKED ISSUE #4405: Directory name used by test_merged_config is not rust unique
`test_merged_config()` in _confi.rs_ creates and uses folder name **`a`**, usually under `/tmp` directory.  The problem is that `/tmp/a` is a commonly used for other purposes, and that can cause problems as happened to me in #4400.  It would be better if a more **rust unique name** will be used instead of "a".

### PR DESCRIPTION
**Pull request by mgrachev**
Fix #4405

### CODE REVIEW

**Comment by mgrachev** [comment]
I have broken all tests 🙈

**Comment by calebcartwright** [comment]
> I have broken all tests see_no_evil sweat_smile

No worries, that's unrelated to the changes here. Try rebasing to grab the latest changes from master

**Comment by mgrachev** [comment]
> No worries, that's unrelated to the changes here. Try rebasing to grab the latest changes from master

Thank you! All tests are passed 🙌

**Review by topecongiro — APPROVED** [review]
LGTM. Thank you for your contribution!

**Pull request merged**
