### PR TITLE
[rustfmt 1.x] fix formatting arbitrary extern abi

### PR DESCRIPTION
**Pull request by calebcartwright**
Refs #4086

### CODE REVIEW

**Comment by calebcartwright** [comment]
Feel free to update the target branch as needed. Only opened the PR against the 1.4.12 branch because a 1.4.13 branch doesn't exist.

**Comment by calebcartwright** [comment]
Same spurious AppVeyor failure

```bash
cargo 1.44.0-nightly (7019b3ed3 2020-03-17)
cargo build --verbose
    Updating crates.io index
error: failed to get `annotate-snippets` as a dependency of package `rustfmt-nightly v1.4.13 (C:\projects\rustfmt)`
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  error inflating zlib stream; class=Zlib (5)
Command exited with code 101
```

**Comment by topecongiro** [comment]
LGTM, thanks!

**Pull request merged**
