### PR TITLE
refactor - show file path in error message when parsing config from toml

### LINKED ISSUE #6302: Better error message
I ran into a problem that was resolved by looking at #2057. It took longer than I'd like and the error message is not too helpful. 

Currently if the project doesn't have `rustfmt.toml` in the workspace, `cargo fmt` checks all parent directories for a configuration file. This is not the expected behaviour, because as a user of Rust one assumes that going to the parent ends at the nearest workspace (and workspaces can't be nested). As such it is unclear which configuration file failed to parse. 

So, the error message that looks like this, 
```
Error: Decoding config file failed:
invalid type: integer `2021`, expected string
in `edition`

Please check your config file.
```

Should really read as more like this: 
```
The file `/home/user/git/rustfmt.toml` failed to parse. 
Invalid type: Integer `2021`, expected string 

Please check `/home/user/git/rustfmt.toml`. 
```

Ideally, of course the error message can be brought in line with the quality of `rustc` errors, looking more like 

```
The file `/home/user/git/rustfmt.toml` failed to parse. 
The `edition` variable has the wrong type: expected string, got 2021 (Integer). 

21: edition = 2021 

help: Add double quotes around `2021` in `/home/user/git/rustfmt.toml:21`. 
```

### PR DESCRIPTION
**Pull request by ytmimi**
Fixes #6302

Display the path to the toml config file that rustfmt failed to parse configurations from.

### CODE REVIEW

**Comment by ytmimi** [comment]
@rufevean opening up this PR instead of https://github.com/rust-lang/rustfmt/pull/6310. Not sure what the issue was but this  contains all your work boiled down into a single commit. Thanks for you help!

**Comment by rufevean** [comment]
> @rufevean opening up this PR instead of #6310. Not sure what the issue was but this contains all your work boiled down into a single commit. Thanks for you help!

thats awesome, thanks a lot for your guidance.

**Comment by ytmimi** [comment]
@rufevean I think we're all set! Just rerunning the failed integration job right now, but assuming that it passes I'll get this merged

**Comment by rufevean** [comment]
Awesome,thank you

**Pull request merged**
