### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by light4**
itertools 0.9 -> 0.10
unicode-segmentation 1.0.0 -> 1.9.0
regex 1.0 -> 1.5
term 0.6 -> 0.7
env_logger 0.8 -> 0.9
unicode-width 0.1.5 -> 0.1.9
dirs 2.0.1 -> 4.0.0
ignore 0.4.17 -> 0.4.18
annotate-snippets 0.8 -> 0.9
lazy_static 1.0.0 -> 1.4.0

### CODE REVIEW

**Comment by ytmimi** [comment]
Thanks for your first contribution to the project and for helping to keep the dependencies up to date! Looks good to me!

**Comment by calebcartwright** [comment]
Thanks for this. I've been meaning to take a look at the deps for a while, but there's some subtle complexity that only surfaces upstream in rust-lang/rust where rustfmt and other tools are consumed as git submodules or subtrees. There was one that's always a pain but I can never seem to remember which one it is.

I suspect this will be fine but need to do a little digging first before proceeding

**Comment by light4** [comment]
I think it's `rls`.

```shell
❯ rg --fixed-strings 'git+' --type toml
src/tools/rls/Cargo.lock
129:source = "git+https://github.com/rust-lang/cargo?rev=1c034752de0df744fcd7788fcbca158830b8bf85#1c034752de0df744fcd7788fcbca158830b8bf85"
134: "cargo-platform 0.1.2 (git+https://github.com/rust-lang/cargo?rev=1c034752de0df744fcd7788fcbca158830b8bf85)",
196:source = "git+https://github.com/rust-lang/cargo?rev=1c034752de0df744fcd7788fcbca158830b8bf85#1c034752de0df744fcd7788fcbca158830b8bf85"
204:source = "git+https://github.com/rust-lang/cargo?rev=1c034752de0df744fcd7788fcbca158830b8bf85#1c034752de0df744fcd7788fcbca158830b8bf85"
289:source = "git+https://github.com/rust-lang/rust-clippy#496f26c2297c0117a24c3d26172fd72b5f9ad927"
310:source = "git+https://github.com/rust-lang/rust-clippy#496f26c2297c0117a24c3d26172fd72b5f9ad927"
370:source = "git+https://github.com/rust-lang/cargo?rev=1c034752de0df744fcd7788fcbca158830b8bf85#1c034752de0df744fcd7788fcbca158830b8bf85"
1875:source = "git+https://github.com/rust-lang/rustfmt?rev=5056f4cfb311a084420f1828cd58af94d143f5e0#5056f4cfb311a084420f1828cd58af94d143f5e0"
1885:source = "git+https://github.com/rust-lang/rustfmt?rev=5056f4cfb311a084420f1828cd58af94d143f5e0#5056f4cfb311a084420f1828cd58af94d143f5e0"

compiler/rustc_codegen_gcc/Cargo.lock
44:source = "git+https://github.com/antoyo/gccjit.rs#0672b78d162d65b6f36ea4062947253affe9fdef"
52:source = "git+https://github.com/antoyo/gccjit.rs#0672b78d162d65b6f36ea4062947253affe9fdef"

compiler/rustc_codegen_cranelift/Cargo.lock
14:source = "git+https://github.com/bjorn3/rust-ar.git?branch=do_not_remove_cg_clif_ranlib#de9ab0e56bf3a208381d342aa5b60f9ff2891648"
```

**Comment by calebcartwright** [comment]
> I think it's rls.

Nah that's not what I was thinking of. There used to be a ceiling on one of these due to the workspace hack but I think that may have been sorted. I'm waiting for a couple PRs to land in rust-lang/rust before syncing the subtree over here as they have some relevant changes. Apologies in advance as there's a decent change that will introduce some merge conflicts for this PR, but it's been too long since I've done a sync and I need to get the upstream changes incorporated here.

Will drop a note when that's done so you'll know when to rebase and deal with any conflicts

**Comment by calebcartwright** [comment]
Upstream changes have been pulled in, happy to move forward with this after you rebase and address conflicts :+1:

**Comment by light4** [comment]
rebased and make the deps sorted

**Review by calebcartwright — APPROVED** [review]
Thanks! I'm going to squash these to make things a tad easier to revert on the off chance any of these changes end up causing problems upstream in the subtree

**Pull request merged**
