### PR TITLE
Fixed 'Incorrect comment indent inside if/else' issue.

### LINKED ISSUE #4120: Incorrect comment indent inside if/else
Example:
```rust
fn main() {
    let x = if true {
        1
    // comment with wrong indent
    } else {
        0
    };
}
```
(And no, this definitely should not be a comment on the `else` — actually, it should not be rustfmt's decision whether this applies to the `else` or is a free comment after the `1`.)

### PR DESCRIPTION
**Pull request by whizsid**
Fixes #4120 .

### CODE REVIEW

**Comment by calebcartwright** [comment]
Could you elaborate on the removal of the existing test file?

**Comment by whizsid** [comment]
@calebcartwright It was implemented to test #1575 and there are conflicts between the two cases. And already covered these cases in the new test file.

> And no, this definitely should not be a comment on the else — actually,
> it should not be rustfmt's decision whether this applies to the else or is a free comment after the 1.

Should we need to detect the user's indentation and format the last comment with the user's indentation?

**Comment by whizsid** [comment]
@calebcartwright I changed the PR as you suggested in the comment  https://github.com/rust-lang/rustfmt/issues/4120#issuecomment-705903666 . CI is failing because of a network error.

**Comment by calebcartwright** [comment]
Excellent news @whizsid. I've restarted the GH run as it did indeed look spurious. I didn't get a chance to go through the implementation changes, but did a quick run through the tests added and they look great!

Will try to go through this in more detail tomorrow

**Review by topecongiro — APPROVED** [review]
Thank you for the PR! LGTM.

**Review by calebcartwright — APPROVED** [review]
Well done @whizsid, thank you!

**Pull request merged**
