### PR TITLE
Improve out of line module resolution

### LINKED ISSUE #5119: Rustfmt cannot resolve submodules of integration tests
## Overview

Rustfmt cannot find a submodule of an integration test located in a separate file.

Running `cargo fmt` on a project that contains a submodule `test1/sub1` implemented by the file `tests/test1/sub1.rs` produces the following error message:

```
Error writing files: failed to resolve mod `sub1`: $PACKAGE/tests/test1/test1 does not exist
```

Submodules in integration tests can be created as follows:

In `tests/test1.rs`:
```
mod test1 {
    mod sub1;
    mod sub2;
}
```

The submodules `sub1` and `sub2` can be implemented in the files `tests/test1/sub1.rs` and `tests/test1/sub2.rs`.

This structure works with `cargo build`, `cargo test`, and `cargo clippy`, but fails for `cargo fmt` with the error message given above.

## Steps to reproduce

Clone this repo containing a minimal example illustrating the problem: https://github.com/walkie/rustfmt-test-submodule-issue

From within the repo:

 * Run `cargo test` and observe that the package successfully compiles and the tests in both submodules run and pass.
 * Run `cargo fmt` and observe the following error message:

```
Error writing files: failed to resolve mod `sub1`: [...]/rustfmt-test-submodule-issue/tests/test1/test1 does not exist
```

The same error can also be produced by `rustfmt` directly with the command: `rustfmt tests/test1.rs`

## Expected behavior

 * No Rustfmt I/O errors. :-)

## Other information

 * Installed Rustfmt by `rustup component add rustfmt`
 * Tested with versions `1.51`, `1.57`, and `1.59.0-nightly (48a5999fc 2021-12-01)`
 * Tested on Fedora Workstation 34 and MacOS 11.6.1

The error occurs in all combinations of the above.

### PR DESCRIPTION
**Pull request by ytmimi**
Fixes #5119

When the directory structure was laid out as follows:

```
dir
 |---mod_a
 |    |---sub_mod_1.rs
 |    |---sub_mod_2.rs
 |---mod_a.rs
```

And ``mod_a.rs`` contains the following content:

```rust
mod mod_a {
    mod sub_mod_1;
    mod sub_mod_2;
}
```

rustfmt previously tried to find ``sub_mod_1.rs`` and ``sub_mod_2.rs``
in ``./mod_a/mod_a/``. This directory does not exist and this caused
rustfmt to fail with the error message:

    Error writing files: failed to resolve mod

Now, both ``sub_mod_1.rs`` and ``sub_mod_2.rs`` are resolved correctly
and found at ``mod_a/sub_mod_1.rs`` and ``mod_a/sub_mod_2.rs``.

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thanks for diving into this one! Few things:

- There's a merge conflict now due the sync of the subtree, which ties back to https://github.com/rust-lang/rust/pull/91957 (tl;dr the borrow/deref sigils can be dropped now)
- There's a number of other mod resolution issues and I'm somewhat paranoid about fixing one introducing another. We don't necessarily need to hold off on this, but if you have bandwidth before I get around to reviewing, it would be good to compare to some other issues to see whether they are fixed (and a true, non specious fix) as well as if any older "resolved" issues are impacted but not detected due to inadequate testing

**Comment by ytmimi** [comment]
I fixed the merge conflict!

I understand you wanting to be cautious about not introducing any module resolution issues. Last night I tried to add the ``a-mods`` label to a handful of issues that I thought were module resolution related. I'm sure there are plenty more that I missed, so any help pointing out the more relevant module resolution errors would be greatly appreciated.

I'm also happy to work on another PR to build up our tests around module resolution / work on other module resolution related issues.

As a side note, I don't think this fix will introduce any issues as the behavior is almost identical to how it was before, with the only difference being that we bail early if adding the next path component would lead to an invalid directory path.

**Comment by ytmimi** [comment]
I went ahead and adjusted the current test case to incorporate both the ``#[cfg]`` and ``mod-rs`` to validate the module resolution. It would probably be a little cleaner to have each one of these scenarios be a separate test (and I'm happy to break it up), but this should help verify these changes.

**Comment by calebcartwright** [comment]
> I went ahead and adjusted the current test case to incorporate both the `#[cfg]` and `mod-rs` to validate the module resolution.

To clarify and elaborate, I was referring to some of these test scenarios https://github.com/rust-lang/rustfmt/tree/master/tests/source/cfg_if and https://github.com/rust-lang/rustfmt/tree/master/tests/source/cfg_mod

**Review by calebcartwright — APPROVED** [review]
Still want to poke at this a bit more later on, but should be fine for now (going to wait to merge til after the next sync though)

**Pull request merged**
