### PR TITLE
rustfmt 1.x bump rustc-ap to v671

### PR DESCRIPTION
**Pull request by calebcartwright**
Needed to fix broken toolstate https://github.com/rust-lang/rust/issues/74812

Master was already addressed via #4354 

Racer PR for the same rustc-ap bump opened https://github.com/racer-rust/racer/pull/1124

### CODE REVIEW

**Comment by jonhoo** [comment]
@calebcartwright Looks like CI failed on this one?

**Comment by calebcartwright** [comment]
Thanks @jonhoo. I'm aware, and it's a spurious issue with one of the four appveyor jobs. This happens from time to time with appveyor.

https://ci.appveyor.com/project/rust-lang-libs/rustfmt/builds/34356708
```bash
info: profile set to 'default'
info: setting default host triple to x86_64-pc-windows-gnu
info: syncing channel updates for 'nightly-x86_64-pc-windows-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-nightly.toml.sha256' to 'C:\Users\appveyor\.rustup\tmp\ft7u6n_mzdgt53n7_file'
error: caused by: failed to make network request
error: caused by: error sending request for url (https://static.rust-lang.org/dist/channel-rust-nightly.toml.sha256): error trying to connect: dns error: No such host is known. (os error 11001)
error: caused by: error trying to connect: dns error: No such host is known. (os error 11001)
error: caused by: dns error: No such host is known. (os error 11001)
error: caused by: No such host is known. (os error 11001)
Command exited with code 1
```

**Comment by Aaron1011** [comment]
Is there anything else that needs to be done in order for this PR is merged? The lack of rustfmt on the latest nightlies is blocking https://github.com/solana-labs/solana/pull/11326

**Comment by calebcartwright** [comment]
> Is there anything else that needs to be done in order for this PR is merged? The lack of rustfmt on the latest nightlies is blocking [solana-labs/solana#11326](https://github.com/solana-labs/solana/pull/11326)

Not within this PR, just waiting for @topecongiro as I don't have access to release rustfmt on crates.io. More details on the steps and sequencing required when there's breaking upstream changes described in https://github.com/rust-lang/rust/issues/74812#issuecomment-669168164

**Pull request merged**
