### PR TITLE
Preserve attrs with imports_granularity=Item

### LINKED ISSUE #5030: `imports_granularity=Item` removes `#[cfg()]` attribute from imports
If I format this file
```rust
#[cfg(feature = "foo")]
use std::collections::{
    HashMap,
    HashSet,
};

fn main() {
    println!("Hello, world!");
}
```
with `rustfmt --config imports_granularity=Item`, `rustfmt` removes the `cfg` attribute:
```console
$ rustfmt --config imports_granularity=Item main.rs
```

Output:
```rust
use std::collections::HashMap;
use std::collections::HashSet;

fn main() {
    println!("Hello, world!");
}
```

This only happens if there is more than one import in the `use` statement, i. e. formatting
```rust
#[cfg(feature = "foo")]
use std::collections::{
    HashMap,
};
```
correctly retains the attribute.

`rustfmt` was installed via `rustup`, current nightly:
```console
$ rustfmt --version
rustfmt 1.4.37-nightly (c102653 2021-10-15)
```

### PR DESCRIPTION
**Pull request by 9999years**
Closes #5030 

On the road to #4991

### CODE REVIEW

**Comment by ytmimi** [comment]
Thanks for the PR!

looks like a pretty simple fix to just pass the attributes along, which is great. When you have a chance, could you add test cases for the other variants: ``Preserve``, ``Crate``, ``Module``, ``Item``, ``One``.

**Comment by 9999years** [comment]
#5030 doesn't concern the other variants, which have harder-to-fix bugs. I'll see if I can work on them but it'll be in a separate PR.

**Comment by calebcartwright** [comment]
Thank you for the PR! This seems to be a duplicate of #5031 to me though, and the interactions with the other variants was one of the outstanding questions still unresolved over there (https://github.com/rust-lang/rustfmt/pull/5031#discussion_r753617083)

As such, I think it' be best to either extend the resolution as suggested in #5031 or as @ytmimi suggested, add some cases for other variants to make sure there's no unanticipated side effects.

I don't recall offhand whether the diff is currently on a call path that's only reachable with the `Item` variant, but this portion of the codebase gets refactored frequently enough that the tests are still valuable even if only as a preventative/defensive measure

**Comment by calebcartwright** [comment]
Closing in favor of #5314

**Pull request closed without merging**
