### PR TITLE
Generate semicolon following Loop

### LINKED ISSUE #5377: rustfmt changes return type of loop and causes code to not compile
Most basic example:

```
fn main() {
    loop {
        break false
    };
}
```
This just runs and does nothing.

If you run rustfmt it yields

```
fn main() {
    loop {
        break false;
    }
}

```

This now fails to compile

```
Compiling playground v0.0.1 (/playground)
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
 --> src/main.rs:3:15
  |
3 |         break false;
  |               ^^^^^ expected `()`, found `bool`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

### PR DESCRIPTION
**Pull request by carsonRadtke**
Fixes #5377

`semicolon_for_stmt` determines whether or not a statement should end with a semicolon. In the case of the issue, it was determined that `Semi` statements containing a `Loop` expression should never end with a semicolon. This is not the case as the repro demonstrates. 

I changed the behavior of `semicolon_for_stmt` to always end in a semicolon. 

Note: `While` expressions and `ForLoop` expressions also get the semicolon dropped when found in a `Semi`. The snippet that reproduces for `Loop` had no issue with these other types, so I left the behavior as-is.

### CODE REVIEW

**Comment by ytmimi** [comment]
Thanks for the first time contribution to rustfmt 🎉

Haven't had a chance to review this yet, but out of curiosity, why is `tests/target/issue-5377` a binary file?

**Comment by carsonRadtke** [comment]
That was an oversight, it has been fixed. Thanks for pointing it out.

**Comment by ytmimi** [comment]
Will rustfmt add/remove semicolons if we start with the following input?

```rustfmt
fn must_end_with_semi() {
    loop {
        break false;
    }
}

fn cannot_end_with_semi() -> bool {
    loop {
        break false
    };
}
```

Or is this PR just trying to ensure that if a semicolon exists we don't remove it?

**Comment by calebcartwright** [comment]
Apologies as I've still not had a chance to look at this, but did want to note that any change we make still has to be compliant with the relevant prescriptions codified into the style guide (e.g. https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/statements.md#expressions-in-statement-position, https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#control-flow-expressions) and also have tests that incorporate relevant config options, like [trailing_semicolon](https://rust-lang.github.io/rustfmt/?version=v1.5.0&search=#trailing_semicolon)

**Pull request closed without merging**
