### PR TITLE
Support let-chains

### PR DESCRIPTION
**Pull request by ytmimi**
This PR builds off of the work from #5203, and extendeds it to support the single-line formatting rules described in [r-l/rust#110568](https://github.com/rust-lang/rust/pull/110568)

r? @calebcartwright

### CODE REVIEW

**Comment by calebcartwright** [comment]
Hooray! Thanks for working on this.

I assume this will cover #4955 too?

**Comment by calebcartwright** [comment]
> What's blocking this PR from landing?

Caleb and his review capacity :eyes:

**Review by calebcartwright — APPROVED** [review]
There's a couple positions where comments could potentially appear, though they're not "natural" positions comments would often be placed and even if they do, rustfmt will "recover" them anyway since the underlying ast construct is an expression.

Could be worth a todo in the code, but doesn't need to block. Feel free to merge when ready, want to pull this in before running the release train

**Comment by ytmimi** [comment]
@calebcartwright I'm happy to add a TODO comment (in rewrite_let I assume), We currently don't handle comments well between binary operators https://github.com/rust-lang/rustfmt/issues/3591, So I'm guessing these are the case that you're thinking about:

```rust
fn main() {
   if aaaa && let /* comment */ Some(b) = foo() {}

   if cccc && let Some(d) /* comment */ = foo() {}
}
```

**Comment by calebcartwright** [comment]
> @calebcartwright I'm happy to add a TODO comment (in rewrite_let I assume), We currently don't handle comments well between binary operators #3591, So I'm guessing these are the case that you're thinking about:
> 
> ```rust
> fn main() {
>    if aaaa && let /* comment */ Some(b) = foo() {}
> 
>    if cccc && let Some(d) /* comment */ = foo() {}
> }
> ```

Correct, I was referring to comments contained within the let expression's span

**Comment by ytmimi** [comment]
@calebcartwright I added some TODO comments

**Pull request merged**
