### PR TITLE
Use relative-path for logical path traversal

### LINKED ISSUE #4477: Rustfmt cannot find mod with #[path] on windows
**Describe the bug**

Rustfmt on windows cannot resolve `module` to file if `#[path]` used.

Note, `#[path]` should contain windows-unfriendly relative path.

**To Reproduce**

Use `#[path = "../some-relative-path.rs"]` in code.
Pointed file should be and valid rust source or empty.

```rust
#[path = "../module_foo.rs"]
mod module_foo;
```

Error:
```txt
> cargo fmt -- --check
error: couldn't read \\?\D:\a\rustfmt-issue-4477\rustfmt-issue-4477\src\..\module_foo.rs: The filename, directory name, or volume label syntax is incorrect. (os error 123)
Error writing files: failed to resolve mod `module_foo`: \\?\D:\a\rustfmt-issue-4477\rustfmt-issue-4477\src\..\module_foo.rs does not exist
```

- - -

Check out [demo for this issue][]. Also there is two cases reproduced on GHA:
1. [this error "file not found"](https://github.com/fzzr-/rustfmt-issue-4477/runs/1275346924?check_suite_focus=true)
1. [all is ok, `#[path]` with just filename](https://github.com/fzzr-/rustfmt-issue-4477/runs/1275283163?check_suite_focus=true)

[demo for this issue]: https://github.com/fzzr-/rustfmt-issue-4477

- - -

**Expected behavior**

No rustfmt's IO errors.

**Meta**

- rustfmt versions:
  - rustfmt 1.4.15-stable (530eadf4 2020-06-02) 
  - rustfmt 1.4.15-nightly (aedff61f 2020-05-19)
- From where did you install rustfmt?: rustup, crates.io
- How do you run rustfmt: `rustfmt`, `cargo-fmt`

### PR DESCRIPTION
**Pull request by udoprog**
Fixes #4477

This fixes the longstanding issue where you get the following error in case a relative path is specified on Windows which contains `.` or `..` components:

```text
error: couldn't read \\?\D:\Repo\tokio\tokio\tests\..\src\fs\file.rs: The filename, directory name, or volume label syntax is incorrect. (os error 123)
  --> \\?\D:\Repo\tokio\tokio\tests\fs_file_mocked.rs:28:1
   |
28 | mod file;
   | ^^^^^^^^^

Error writing files: failed to resolve mod `file`: \\?\D:\Repo\tokio\tokio\tests\..\src\fs\file.rs does not exist
```

If you doubt if this issue is still present, you can checkout the Tokio project and give it a spin.

The long version is that paths beginning with `\\?\` on Windows are "raw paths" which [turns of automatic expansion of `.` and `..`](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#win32-file-namespaces) causing them to be treated as files and not current and parent directory. Joining them using the regular method as provided by `Path` causes `.` and `..` to be incorrectly included in the absolute path.

These kinds of paths are returned by e.g. the [`fs::canonicalize`](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) implementation on Windows.

For more, see: https://github.com/udoprog/patterns/blob/main/examples/relative-path.rs

Note that an alternative is to avoid path canonicalization in how rustfmt processes things, allowing it to work like `rustc` [since that basically uses the same implementation in how the `path` attribute is expanded](https://github.com/rust-lang/rust/blob/master/compiler/rustc_expand/src/module.rs#L166).

### CODE REVIEW

**Comment by udoprog** [comment]
Note that an alternative is to avoid path canonicalization in how rustfmt processes things, allowing it to work like `rustc` [since that basically uses the same implementation in how the `path` attribute is expanded](https://github.com/rust-lang/rust/blob/master/compiler/rustc_expand/src/module.rs#L166).

**Comment by calebcartwright** [comment]
Thank you for the PR and apologies for the delay. I am going to close this though as I don't want to go in the direction of adding a new dependency and diverging from the logic used within the compiler (we mimic the expansion logic intentionally but don't use it directly since rustfmt operates pre-expansion).

This is actually an issue that was fixed in source on a different branch, and I want to go that route and pull that solution back into the mainline branch.

**Comment by udoprog** [comment]
Cheers. Mind linking to the fix so I can stop using my fork?

**Comment by calebcartwright** [comment]
Sure, but will have to get back to you. There was some odd branch divergence for a while as there were plans for a breaking release of rustfmt that never came to fruition, so I'll need to do a little digging.

**Pull request closed without merging**
