### PR TITLE
Fix formatting of comments in empty structs

### PR DESCRIPTION
**Pull request by Szymongib**
Currently comments in empty structs are formatted weirdly. This PR attempts to fix it by indenting all one line comments to the same one depth indentation.

Example can be found in the issue and tests.

Fixes: #4854

### CODE REVIEW

**Comment by calebcartwright** [comment]
:wave: thanks so much for the PR! will take a closer look at this soon and get back to you with any feedback

**Comment by calebcartwright** [comment]
Thanks again and sorry for the delay! I think we'd need a different fix to really address the issue vs trying to work around a couple of the symptoms. For example, the issue isn't exclusive to line style comments:
```rust
struct Struct {
    /*
     * fsdfsdfsdf
     * sdfsdf
     */
}
```
The issue is really that a struct with no fields and a multiline comment/multiple comments doesn't get formatted with the correct shape. It might be worth seeing if another one of the comment recovery helper functions (like `combine_strs_with_missing_comments`) could be used instead

**Comment by Szymongib** [comment]
Thanks for taking the time to look at it @calebcartwright! 

That is a good point that the other comments types are broken too.

Sorry for delay, it took me a while to figure it out.

The `combine_strs_with_missing_comments` does not seem to do any better job so I ended up using `FmtVisitor::format_missing_no_indent`. 

It seems that now both single line comments as well as multiple/multiline comments work fine.

Thanks again for feedback and let me know if new changes make sense!

**Comment by ytmimi** [comment]
Hey, I know it's been a while since you asked me to review. The fix is actually a lot simpler. The issue is we're not calling ``rewrite_missing_comment`` with the right shape. The shape needs to be block indented so that each comment after the first is properly offset.

@Szymongib could you make this change to ``items::format_empty_struct_or_tuple`` instead.
```diff
-    match rewrite_missing_comment(span, Shape::indented(offset, context.config), context) {
+    // indented shape for proper indenting of multi-line comments
+    let shape = Shape::indented(offset.block_indent(context.config), context.config);
+    match rewrite_missing_comment(span, shape, context) {
```

This change breaks some test, but as far as I can tell each test that is broken explicitly states that the test can be reformatted once 4854 is fixed. For example:
```diff
Mismatch at tests/source\comments-in-lists\wrap-comments-true.rs:43:

 pub struct S2 {
     // This can be changed once https://github.com/rust-lang/rustfmt/issues/4854 is fixed
-// Expand as needed, numbers should be ascending according to the stage
-// through the inclusion pipeline, or according to the descriptions
+    // Expand as needed, numbers should be ascending according to the stage
+    // through the inclusion pipeline, or according to the descriptions
 }
```

**Comment by Szymongib** [comment]
Thanks @ytmimi it is indeed a much simpler fix, I see tho that branches changed so I will open another PR against master.

**Pull request closed without merging**
