### PR TITLE
5978 Trailing whitespaces are stripped in raw string literals in doc tests

### PR DESCRIPTION
**Pull request by IVIURRAY**
Fixes issue: https://github.com/rust-lang/rustfmt/issues/5978

WIP: Have created the test for this feature just need to implement the code.

### CODE REVIEW

**Comment by ytmimi** [comment]
Thanks for picking this up! based on my up front investigation I suspect this will be tricky one to solve (but I could be wrong). If you're looking for a good first issues to work on I might be able to find a few from the backlog.

**Comment by IVIURRAY** [comment]
Ok, I'm a little stuck on this one. Wondering if I can get some help. I've read over the documentation provided on the github page and followed the advice on https://github.com/rust-lang/rustfmt/issues/5978#issuecomment-1853078993 but still struggling to understand where to make this change.

https://github.com/rust-lang/rustfmt/blob/2174e6052dcb1802417d686140fe0ab7cbef0df2/src/comment.rs#L376C1-L383

I can see on the above code block I'm getting the following output. Now, I what I don't understand is if I should have the `r#""` block as its own `Span` to be processed or if I should process it as part of this snippet.

```rust 
/// String literal test
/// ```rust
/// let expected = "\nfoo \n";
/// assert_eq!(expected, r#"
/// foo
/// "#);
/// ```
```

I'm thinking if I was to process this in its own snippet then I would probably mark some sort of "is inside raw code block" variable and not touch the following lines until I see the `"#` end.

Would apprechiate some help on this one :)

**Comment by IVIURRAY** [comment]
@ytmimi - ha you must've been reading my mind. I just commeted for help as you replied.

I did look over the "good first issue" tags but nothing took my fancy or I just didn't understand that is why I opted for a more recent issue. I am looking to get more involved in Rust so any issues you fire my way I will happily try to take a look (maybe with some guidence).

**Comment by ytmimi** [comment]
@IVIURRAY great to hear that you want to get more involved! The team greatly appreciates the help 🙏🏼! For now, take a look at #5801. If you need help feel free to reach out on [Rust’s Zulip](https://rust-lang.zulipchat.com/) in the `t-rustfmt` stream.

**Pull request closed without merging**
