### PR TITLE
Recognize when a block comment has been ended inside a string literal…

### LINKED ISSUE #4312: Multiline comments ending in " lead to creation of line with only spaces
**Input**

```rust
fn main() {
    /* " */
    println!("Hello, world!");
}
```

**Output**

```rust
fn main() {
    /* " */
    
    println!("Hello, world!");
}
```
(notice the blank line between the comment and the println, containing 4 spaces.

**Expected output**

Input unchanged.

**Meta**

- rustfmt version: `rustfmt 1.4.16-stable (939e164 2020-06-11)`
- From where did you install rustfmt?: rustup

### PR DESCRIPTION
**Pull request by ChinYing-Li**
Back-porting the change in #4320 to branch `rustfmt-1.4.37`.
This would fix #4312 and its duplicate, #4744 .
Any suggestion is appreciated!

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thank you for this, LGTM! Could you also do me a favor and add a file to cover another duplicate (#4806)?

**Comment by ChinYing-Li** [comment]
I added the case in #4806 to `issue-4312`, as I think it is only a few lines and identical to one of the cases in `issue-4312`.

**Comment by calebcartwright** [comment]
Thank you for adding the additional case! That's fine for now, but for future reference the preference is to either have file+issue specific pairs, or a separate file not named for any one issue if that file will contain cases from multiple issues

**Review by calebcartwright — APPROVED** [review]
:heart:

**Pull request merged**
