### PR TITLE
Add test for nested tuple access

### PR DESCRIPTION
**Pull request by sasurau4**
Helps with #4470 

- pass `cargo make test`

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thank you for the PR @sasurau4 adding the tests! Be sure to review the additional comments (like https://github.com/rust-lang/rustfmt/issues/4470#issuecomment-719170245) on the linked issue that call out a minor code change we want to make as well

**Comment by sasurau4** [comment]
@calebcartwright Thanks for pointing out. I fixed!

**Comment by calebcartwright** [comment]
Perfect thank you.

Changes LGTM, though would you mind doing me a favor and including the below snippets in the tests too? They'll be formatted fine here but since these uses cases were reported in #4543 I'd like to include them in the test suite to prevent any future regressions

```rust
let oid = oid!(1.2.840.113549.1.1.5);
let oid2 = oid!(2.5.4.3);
```

**Review by calebcartwright — APPROVED** [review]
:+1:

**Comment by sasurau4** [comment]
@calebcartwright Thanks for your review. I added the test for issue-4543 :+1:

**Comment by calebcartwright** [comment]
Thanks!

**Pull request merged**
