### PR TITLE
add document describing rustfmt's stabilisation process

### LINKED ISSUE #3197: Process for config option stabilisation
The `trailing_semicolon` configuration for example is currently unstable. What needs to happen in order for it to be stabilized?

(I would like to use it in a project that is otherwise compatible with the Stable channel.)

### PR DESCRIPTION
**Pull request by scampi**
Close #3197

### CODE REVIEW

**Comment by scampi** [comment]
@topecongiro what do you think about the proposed process ? Is it OK to be in a separate file or you'd prefer it in an existing one, e.g., `Contributing.md` ?

**Comment by topecongiro** [comment]
@scampi Sorry about the delay, I have missed the notification 😞 

Having this kind of documentation sounds good to me in general. Thank you for writing this up! W.r.t. stabilizing configuration option, however, I think we may first want to consider whether the current interface and design is good enough for stabilization. Could refer to it in this documentation?

**Comment by scampi** [comment]
@topecongiro I have added a condition taken from your comment.

**Comment by topecongiro** [comment]
@scampi Thank you!

**Pull request merged**
