### PR TITLE
Subtree push 2023-12-12

### PR DESCRIPTION
**Pull request by ytmimi**
syncing with (`r-l/rust` [21cce21d](https://github.com/rust-lang/rust/commit/21cce21d8c012f14cf74d5afddd795d324600dac) 2023-12-11)

Here's my first pass at doing the subtree push. I'm not sure if we're ready to do the full sync yet, but I wanted to get some hands on practice with the process. I followed the [clippy docs](https://doc.rust-lang.org/nightly/clippy/development/infrastructure/sync.html), and applied those instructions to rustfmt.

r? @calebcartwright

### CODE REVIEW

**Comment by ytmimi** [comment]
Running the [Diff-Check job](https://github.com/rust-lang/rustfmt/actions/runs/7184737071)

**Comment by calebcartwright** [comment]
Great! Glad you were able to pick this up and get your local env all set up, will take a look after work today

**Comment by ytmimi** [comment]
Thanks Caleb!

**Review by calebcartwright — APPROVED** [review]
thanks!

**Pull request merged**
