### PR TITLE
Added Updated default version to Rustfmt docs config

### LINKED ISSUE #4633: Change default version used in configuration website from master to latest 1.x
rustfmt has a documentation site that enumerates all the configuration options available for a given version of rustfmt

https://rust-lang.github.io/rustfmt/

The site allows users to specify which version of rustfmt they want config documentation for, because the available/support config options can vary from one version of rustfmt to another (i.e. rustfmt v1.4.30 has different options than rustfmt v1.4.12)

The _default_ rustfmt version used on the site is actually pointing the `master` branch in the rustfmt source repo itself. However, this has proven to be problematic because:
* there's a huge difference between the configuration options in source control and the 1.x versions of rustfmt that are distributed and used by the community
* most users still don't realize/understand they need to select the version on the config site to match the version of rustfmt they are actually using
* there are comparatively very, very few users building and using rustfmt from source, so the current default of `master` is not a good default because it requires the vast majority of users to need to take an additional action on the config site.

The ask for this issue is to change that default from `master` to a different, new default. Ideally, the default could somehow be dynamically set to the latest (semver) `v1.*` version from the list, though if that proves impossible/too complex then simply hardcoding it to a different value (like `v1.4.31`) would suffice, and the rustfmt team will manually update that hardcoded value to the next value when we release a new version of rustfmt.

The code for the config site can be found here:
https://github.com/rust-lang/rustfmt/blob/master/docs/index.html

### PR DESCRIPTION
**Pull request by gunadhya**
Fixes (mostly) #4633 
**Changes:**
Updates the default version to the latest version released.

### CODE REVIEW

**Review by calebcartwright — APPROVED** [review]
Beautiful thank you! :heart:

**Comment by calebcartwright** [comment]
FYI I tweaked the PR description to prevent closing the issue just yet. This change addresses the main issue so I wanted to go ahead and get it out ASAP, but there's a few other edge cases I'd like to tweak as well, for example ensuring the page default is something other than `master` even if any of the API calls fail:

https://github.com/rust-lang/rustfmt/blob/19b34fe7eb4e002217fa78c60d9c52dac711b09c/docs/index.html#L101

Let me know if you'd be interested in working on that, or really anything else, as there's some other improvements I'd like to see in the config docs as well

**Comment by jdahlstrom** [comment]
The doc page does not appear to honor the `version` GET parameter (anymore?) For example, browse to https://rust-lang.github.io/rustfmt/?version=master&search=#array_width and observe that after a brief flash of correct content, the selected version resets to 1.4.32, the `array_width` and other non-1.* sections are hidden, and the browser scroll position becomes incorrect.

**Comment by gunadhya** [comment]
> The doc page does not appear to honor the `version` GET parameter (anymore?) For example, browse to https://rust-lang.github.io/rustfmt/?version=master&search=#array_width and observe that after a brief flash of correct content, the selected version resets to 1.4.32, the `array_width` and other non-1.* sections are hidden, and the browser scroll position becomes incorrect.

@jdahlstrom My bad. I'll try to figure out the cause and find a better way.

**Comment by calebcartwright** [comment]
Thanks for the report @jdahlstrom!

**Pull request merged**
