### PR TITLE
Switch to tracing for logging

### PR DESCRIPTION
**Pull request by fee1-dead**

### CODE REVIEW

**Comment by calebcartwright** [comment]
changes lgtm, but would you rebase when you get a chance? i had to modify the lockfile after the last subtree sync and would rather have this branch be up to date since it's also touching the lockfile (caution/paranoia, same thing I guess :laughing:)

**Comment by fee1-dead** [comment]
It looks like I could just use GitHub's ui for rebasing since there were no merge conflicts, so I did.

**Comment by ytmimi** [comment]
Hey, @calebcartwright @fee1-dead I'm not sure If i'm doing something wrong, but I'm unable to see any log output when running the latest master rustfmt (f2bad9c). Do we need to add use statements for `tracing::trace!`, `tracing::debug!`, and `tracing::info!` throughout the project?

Using `rustfmt 1.5.3-nightly (f4b80cac 2023-06-30)`:

```
echo "fn main() {}" | RUSTFMT_LOG=rustfmt=DEBUG rustfmt
[2023-07-06T04:31:45Z DEBUG rustfmt_nightly::items] compute_budgets_for_params 7 Indent { block_indent: 0, alignment: 0 }, 0, SameLine
[2023-07-06T04:31:45Z DEBUG rustfmt_nightly::items] rewrite_fn_base: one_line_budget: 89, multi_line_budget: 95, param_indent: Indent { block_indent: 4, alignment: 0 }
[2023-07-06T04:31:45Z DEBUG rustfmt_nightly::formatting] track truncate: 14 2
```

However using `rustfmt 1.6.0-nightly (f2bad9c7 2023-07-05)` produces no log messages:

```
echo "fn main() {}" | RUSTFMT_LOG=rustfmt=DEBUG cargo run --bin rustfmt --
```

**Comment by fee1-dead** [comment]
.. I forgot to test logging before opening this PR. This is my bad. I will put up a PR fixing this soon.

**Comment by fee1-dead** [comment]
If desired, I can also add a compatibility layer for use of `log::debug!` to be redirect to tracing's implementation, but #5818 should fix this for the rustfmt crate at least.

**Pull request merged**
