### PR TITLE
fix: don't force a newline after an empty where clause (master)

### PR DESCRIPTION
**Pull request by meiomorphism**
Rebase of #4548 onto `master`. Clean.

### CODE REVIEW

**Comment by meiomorphism** [comment]
I've looked at several of the CI failures; they all seem to be from `rustc-ap-rustc_data_structures-686.0.0`, due to the recent rename of the `optin_builtin_traits` feature to `auto_traits` (https://github.com/rust-lang/rust/commit/810324d1f31eb8d75e8f0044df720652986ef133).

Presumably updating to 690.0.0 will fix that.

**Comment by calebcartwright** [comment]
Don't worry about the broken CI for now, it's a broken toolstate issue - https://github.com/rust-lang/rust/issues/79407

**Comment by calebcartwright** [comment]
When you get a chance could you rebase on master? CI checks should be good now

**Comment by meiomorphism** [comment]
Pinging, since I've forgotten whether GitHub pings on branch updates, and now suspect that it doesn't.

**Comment by calebcartwright** [comment]
> Pinging, since I've forgotten whether GitHub pings on branch updates, and now suspect that it doesn't.

Thanks. I believe it does, at least for non-rebases, but also entirely possible that I missed this one amongst the notification noise

**Review by calebcartwright — APPROVED** [review]

**Pull request merged**
