### PR TITLE
fix 'extra comma inserted due to comment'

### PR DESCRIPTION
**Pull request by rchaser53**
fix: #3675

### CODE REVIEW

**Comment by rchaser53** [comment]
Yes I can share it. What do you want me to do?
#3680 is a WIP. Should I wait at #3680 merge and add a test to this PR?

**Comment by scampi** [comment]
Just share the inputs in a comment here, i'll add the test case. No need to block this PR.

**Comment by rchaser53** [comment]
I see. Thank you.

**Comment by scampi** [comment]
I'm not able to reproduce the problem in #3680 , could be because I've added another condition to that method...

**Pull request merged**
