### PR TITLE
Fix for handling empty code block in doc comment

### LINKED ISSUE #5234: `format_code_in_doc_comments` causes panic for empty code blocks.
`format_code_in_doc_comments` causes panic for empty code blocks. For instance:

```rust
/// This breaks rustfmt
/// ```
///
/// ```
fn tester() {}
```

# Reproducing
- Clone https://github.com/andrewgazelka/rustfmt-err
- Use `cargo 1.61.0-nightly (ea2a21c99 2022-02-15)`
- Run `cargo fmt -- --check`

```
thread 'main' panicked at 'begin <= end (12 <= 11) when slicing `fn main() {}
`', src/tools/rustfmt/src/lib.rs:399:47
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::str::slice_error_fail
   3: rustfmt_nightly::format_code_block
   4: rustfmt_nightly::comment::rewrite_comment_inner
   5: rustfmt_nightly::comment::identify_comment
   6: rustfmt_nightly::attr::rewrite_initial_doc_comments
   7: <[rustc_ast::ast::Attribute] as rustfmt_nightly::rewrite::Rewrite>::rewrite
   8: <rustfmt_nightly::visitor::FmtVisitor>::visit_attrs
   9: <rustfmt_nightly::visitor::FmtVisitor>::visit_item
  10: <rustfmt_nightly::visitor::FmtVisitor>::visit_items_with_reordering
  11: <rustfmt_nightly::visitor::FmtVisitor>::format_separate_mod
  12: rustfmt_nightly::formatting::format_project::<rustfmt_nightly::Session<std::io::stdio::Stdout>>
  13: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::with::<<rustfmt_nightly::Session<std::io::stdio::Stdout>>::format_input_inner::{closure#0}, core::result::Result<rustfmt_nightly::FormatReport, rustfmt_nightly::ErrorKind>>
  14: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_span::create_session_if_not_set_then<core::result::Result<rustfmt_nightly::FormatReport, rustfmt_nightly::ErrorKind>, <rustfmt_nightly::Session<std::io::stdio::Stdout>>::format_input_inner::{closure#0}>::{closure#0}, core::result::Result<rustfmt_nightly::FormatReport, rustfmt_nightly::ErrorKind>>
  15: <rustfmt_nightly::Session<std::io::stdio::Stdout>>::format
  16: rustfmt::format_and_emit_report::<std::io::stdio::Stdout>
  17: <rustfmt_nightly::Session<std::io::stdio::Stdout>>::override_config::<rustfmt::format::{closure#0}, ()>
  18: rustfmt::execute
  19: rustfmt::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

# Related
- https://github.com/rust-lang/rustfmt/issues/3986

### PR DESCRIPTION
**Pull request by davidBar-On**
Fixes #5234

Suggested fix is by trimming the code block, as discussed in (now obsolete) PR #4902.

### CODE REVIEW

**Review by ytmimi — APPROVED** [review]
Thank you for opening up this new PR!

**Comment by tgross35** [comment]
Related open PR: #5235

**Comment by ytmimi** [comment]
@tgross35 thanks, I was aware of the other PR and was planning on closing it. Will do so now

**Comment by calebcartwright** [comment]
While I think there's little rationale and utility in practice for having a doc comment codeblock with nothing but whitespace, and obviously a panic is unacceptable, but do we feel that trimming that whitespace is the correct/desirable behavior?

**Comment by tgross35** [comment]
Imho I generally expect rustfmt to eliminate unneeded whitespace, so I would say yes. This would be consistent with what happens when it gets a file with no content and only blank lines - it removes them.

**Comment by calebcartwright** [comment]
> Imho I generally expect rustfmt to eliminate unneeded whitespace, so I would say yes. This would be consistent with what happens when it gets a file with no content and only blank lines - it removes them.

Yeah that's a fair way of looking at it :+1:

**Review by calebcartwright — APPROVED** [review]

**Pull request merged**
