### PR TITLE
use std::lazy::SyncLazy instead of lazy_static

### PR DESCRIPTION
**Pull request by light4**
Can we use the nightly feature `once_cell`?

### CODE REVIEW

**Comment by ytmimi** [comment]
Thanks for your first PR!

> Can we use the nightly feature `once_cell`?

Speaking for myself, I don't see why we couldn't use it. I'm personally not too familiar with the `once_cell` feature. It would be great if you could elaborate on the advantages to using this over `lazy_static!`. Is the idea just to replace a 3rd party dependency?

**Comment by light4** [comment]
1. Remove a 3rd party dependency
2. Macro free
3. When the feature is stabled, we can just switch over it
4. Performance improvement according to this <https://github.com/async-rs/async-std/issues/406> 

This is the `once_cell` tracing issue: <https://github.com/rust-lang/rust/issues/74465>

**Comment by ytmimi** [comment]
That all sounds awesome! Thanks for including those links. I'll be sure to give them a read 😄

**Comment by calebcartwright** [comment]
Thanks for the PR!

We've historically stayed away from any gated features (obviously excluding rustc_private which we need for consuming compiler internals). However, I think we're kidding ourselves if we continue that refrain in the hopes of being able to build with a stable compiler some day.

That being said, I'm still on the fence about this one as I don't think it buys us all that much just yet, given that `lazy_static` is still in our build graph due to various transitive dependencies and we'd technically be pulling in `once_cell` too.

I concur that this is the right move strategically, but not quite convinced yet that it's all that beneficial today. Will leave it parked for a bit in case I change my mind.

**Comment by ytmimi** [comment]
This one is still on hold, but I wanted to mention that the latest tracking issue for this is https://github.com/rust-lang/rust/issues/109736.

**Comment by ytmimi** [comment]
lazy_static was removed in #6154

**Pull request closed without merging**
