### PR TITLE
Fix missing struct field separators under certain conditions

### LINKED ISSUE #4791: Comma deleted if followed by empty line
**Describe the bug**

Define a struct with empty lines, as shown below:
```
pub struct Segment {
    header: SegmentHeader,
    
    end:    SegmentEnd
}
```

format the document (using IDE functionality which relies on rustfmt or by calling `cargo fmt`). Result looks like:
```
pub struct Segment {
    header: SegmentHeader

    end: SegmentEnd
}
```

**To Reproduce**

Start on a brand new project. Have all your standard project template setup and ready to start (incl. rustfmt.toml). Feel totally overwhelmed by all the new information you just gathered. Setup some basic structs. Put an empty line between two struct elements and format the document.

**Expected behavior**

rustfmt reformats the document. While doing so, some artificial intelligence hidden deep inside rustfmt realizes that Segment actually is a wrong point to start at. For such reason rustfmt deletes the comma and all the struct just before it magically implements some perfectly working UN/edifact serialization code.

**Meta**

- rustfmt version: rustfmt 1.4.36-nightly (7de6968 2021-02-07)
- From where did you install rustfmt?: I guess rustup, but system is running stable for years now... i.e., I am not sure
- How do you run rustfmt: IDE (vscode with rust-analyzer) calls rustfmt directly, cargo fmt was executed for test
- my rustfmt.toml:
```
edition = "2018" 
enum_discrim_align_threshold = 30
format_macro_matchers = true 
imports_indent = "Visual"
license_template_path = ".license.template"
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
struct_field_align_threshold = 30
trailing_comma = "Never"
unstable_features = true
where_single_line = true
max_width = 200
```

### PR DESCRIPTION
**Pull request by cassaundra**
Fixes #4791 and #4928.

When `struct_field_align_threshold` is non-zero and `trailing_comma` is set to `Never`, struct field separators are omitted between field groups, resulting in invalid code. This issue is resolved by forcing separators between groups.

A test is included with a minimal reproducible example adapted from the original issue.

### CODE REVIEW

**Comment by calebcartwright** [comment]
@ytmimi if/when you get a chance could you take a look at this? At some point we had a different fix for this that can be found over on the 2.0 branch, so would like to compare this approach vs. that one. I also feel like you may have possibly done some somewhat similar work recently and thought you may be interested in reviewing

**Comment by ytmimi** [comment]
Sure thing! I'll try to find the fix on the 2.0 branch to compare it to and will hopefully be able to get the review done in the next few days. I'll let you know if I run into any issues.

**Comment by ytmimi** [comment]
I managed to track down #4201, which I believe is the PR that fixes this issue on the 2.0 branch. Both fixes are very similar and involve passing additional information to ``rewrite_aligned_items_inner``. The previous PR passes a slice of the remaining fields to ``rewrite_aligned_items_inner``, while the new proposal just passes a boolean. I happen to prefer the newer solution since it's a little more flexible in case there are other scenarios that we need to force trailing separators.

I'm happy with the changes as they are! @cassaundra If you have time would it be possible to add test cases with ``trailing_comma=Always`` and test cases where ``struct_field_align_threshold=0``. Since these are the two configuration options that you need to reproduce the issue it would be great if we had test cases that fully covered their interaction in this scenario.

**Comment by cassaundra** [comment]
Thank you for the review! I will add those test cases soon.

**Comment by cassaundra** [comment]
Apologies for the late response.

I've added the tests as requested, hopefully providing better coverage between `struct_field_align_threshold` and `trailing_comma`. The tests are located in `tests/{source,target}/issue-4791/` and are named as follows:
<table>
<thead>
  <tr>
    <th></th>
    <th scope="col">zero</th>
    <th scope="col">non-zero</th>
  </tr>
</thead>
<tbody>
  <tr>
    <th scope="row">always</th>
    <td>(default)</td>
    <td><code>trailing_comma.rs</code></td>
  </tr>
  <tr>
    <th scope="row">never</th>
    <td><code>no_trailing_comma.rs</code></td>
    <td><code>buggy.rs</code></td>
  </tr>
</tbody>
</table>

**Comment by ytmimi** [comment]
Thanks for adding those additional test cases! I think we now have the test coverage we need. @calebcartwright, is there anything else you'd like to see added? If not, I'm happy to move forward with these changes.

**Comment by calebcartwright** [comment]
Changes LGTM! @cassaundra would you mind adding test files for #4928 too?

**Comment by cassaundra** [comment]
Sorry again for the late reply! It's been a crazy month. Those tests have now been added.

**Comment by ytmimi** [comment]
@cassaundra Thanks for including that additional test!

**Review by calebcartwright — APPROVED** [review]
Awesome, thanks so much!

**Pull request merged**
